-- =====================================================
-- Atiman Finding Assessment
-- Implements the Assessment stage of the Atiman operational flow
-- (ATM-000 sections 9-10, ATM-002 sections 7.2-7.3 and 8.2-8.3):
--
--   Inspection -> Finding -> Assessment -> Action -> Closure
--
-- An assessment is the accountable decision that gives a finding exactly one
-- outcome: Operator Corrected, Monitor, or Escalate. The accountable party may
-- confirm the recommended outcome or override it, and an override requires a
-- reason (ATM-002 section 8.3).
--
-- Scope:
-- - finding_assessments: append-only assessment records with attribution,
--   recommendation, accountable confirmation/override, and outcome detail.
-- - findings: Atiman lifecycle columns (outcome, assessment_state, assessed_at,
--   closed_at) and an extended status set covering the Atiman lifecycle.
--
-- Out of scope (explicitly deferred):
-- - Action execution and closure evidence capture.
-- - EAM escalation package construction and outbound exchange.
-- - Monitor reminder scheduling.
-- - Intelligence-assisted recommendation.
-- - Backfill of pre-existing findings.
--
-- Forward-only: migrations 001-012 are not modified. Idempotent:
-- CREATE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS / guarded constraints.
-- =====================================================

-- =====================================================
-- PART 1 — finding_assessments
-- Append-only record of an accountable finding assessment.
-- =====================================================

CREATE TABLE IF NOT EXISTS finding_assessments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id INTEGER NOT NULL,
    finding_id INTEGER NOT NULL,
    recommended_outcome varchar(50) NOT NULL
        CONSTRAINT chk_finding_assessments_recommended_outcome
        CHECK (recommended_outcome IN ('operator_corrected', 'monitor', 'escalate')),
    confirmed_outcome varchar(50) DEFAULT NULL
        CONSTRAINT chk_finding_assessments_confirmed_outcome
        CHECK (confirmed_outcome IS NULL OR confirmed_outcome IN ('operator_corrected', 'monitor', 'escalate')),
    assessment_state varchar(50) NOT NULL DEFAULT 'pending'
        CONSTRAINT chk_finding_assessments_state
        CHECK (assessment_state IN ('pending', 'confirmed', 'rejected', 'more_evidence_requested')),
    recommended_by_user_id INTEGER NOT NULL,
    assessor_user_id INTEGER DEFAULT NULL,
    engineering_context text,
    override_reason text,
    monitor_interval_days INTEGER DEFAULT NULL,
    escalation_reference varchar(100) DEFAULT NULL,
    rejection_reason text,
    assessed_at TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_finding_assessments_finding
        FOREIGN KEY (finding_id) REFERENCES findings(id) ON DELETE CASCADE,
    CONSTRAINT fk_finding_assessments_organization
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_finding_assessments_recommended_by
        FOREIGN KEY (recommended_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_finding_assessments_assessor
        FOREIGN KEY (assessor_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    -- A confirmed assessment must name its accountable party and when.
    CONSTRAINT chk_finding_assessments_confirmed_requires_accountability
        CHECK (
            assessment_state <> 'confirmed'
            OR (confirmed_outcome IS NOT NULL AND assessor_user_id IS NOT NULL AND assessed_at IS NOT NULL)
        ),
    -- Overriding the recommended outcome requires a reason (ATM-002 8.3).
    CONSTRAINT chk_finding_assessments_override_requires_reason
        CHECK (
            confirmed_outcome IS NULL
            OR confirmed_outcome = recommended_outcome
            OR (override_reason IS NOT NULL AND length(btrim(override_reason)) > 0)
        ),
    -- Monitor requires a reminder interval (ATM-002 7.3).
    CONSTRAINT chk_finding_assessments_monitor_requires_interval
        CHECK (
            confirmed_outcome IS DISTINCT FROM 'monitor'
            OR (monitor_interval_days IS NOT NULL AND monitor_interval_days > 0)
        ),
    -- Escalate requires the escalation package reference for the EAM boundary.
    CONSTRAINT chk_finding_assessments_escalate_requires_reference
        CHECK (
            confirmed_outcome IS DISTINCT FROM 'escalate'
            OR (escalation_reference IS NOT NULL AND length(btrim(escalation_reference)) > 0)
        ),
    -- Rejection must be explained.
    CONSTRAINT chk_finding_assessments_rejection_requires_reason
        CHECK (
            assessment_state <> 'rejected'
            OR (rejection_reason IS NOT NULL AND length(btrim(rejection_reason)) > 0)
        )
);

-- At most one assessment may await a decision for a given finding, so a
-- replayed or concurrent assess request cannot open parallel pending records.
CREATE UNIQUE INDEX IF NOT EXISTS uq_finding_assessments_one_pending_per_finding
    ON finding_assessments (finding_id)
    WHERE assessment_state = 'pending';

CREATE INDEX IF NOT EXISTS idx_finding_assessments_finding
    ON finding_assessments (finding_id);

CREATE INDEX IF NOT EXISTS idx_finding_assessments_organization_state
    ON finding_assessments (organization_id, assessment_state);

CREATE INDEX IF NOT EXISTS idx_finding_assessments_assessor
    ON finding_assessments (assessor_user_id);

-- =====================================================
-- PART 2 — findings: Atiman lifecycle columns
-- =====================================================

ALTER TABLE findings ADD COLUMN IF NOT EXISTS outcome varchar(50) DEFAULT NULL;
ALTER TABLE findings ADD COLUMN IF NOT EXISTS assessment_state varchar(50) NOT NULL DEFAULT 'unassessed';
ALTER TABLE findings ADD COLUMN IF NOT EXISTS assessed_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE findings ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ DEFAULT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_findings_outcome'
          AND conrelid = 'findings'::regclass
    ) THEN
        ALTER TABLE findings
            ADD CONSTRAINT chk_findings_outcome
            CHECK (outcome IS NULL OR outcome IN ('operator_corrected', 'monitor', 'escalate'));
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_findings_assessment_state'
          AND conrelid = 'findings'::regclass
    ) THEN
        ALTER TABLE findings
            ADD CONSTRAINT chk_findings_assessment_state
            CHECK (assessment_state IN ('unassessed', 'pending', 'assessed', 'rejected', 'more_evidence_requested'));
    END IF;
END
$$;

-- The confirmed outcome and the assessment lifecycle must agree: a finding
-- cannot carry an outcome while still being unassessed.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_findings_outcome_requires_assessment'
          AND conrelid = 'findings'::regclass
    ) THEN
        ALTER TABLE findings
            ADD CONSTRAINT chk_findings_outcome_requires_assessment
            CHECK (
                outcome IS NULL
                OR (assessment_state = 'assessed' AND assessed_at IS NOT NULL)
            );
    END IF;
END
$$;

-- Extend the finding status set with the Atiman lifecycle states while keeping
-- the historical states valid. Forward-only: migration 004 is not modified.
ALTER TABLE findings DROP CONSTRAINT IF EXISTS chk_findings_status;
ALTER TABLE findings
    ADD CONSTRAINT chk_findings_status
    CHECK (status IN (
        'open', 'notified', 'in_progress', 'closed', 'cancelled',
        'assessed', 'monitored', 'escalated', 'resolved'
    ));

-- The outcome-bearing lifecycle states are reachable only through a confirmed
-- assessment. Without this, the legacy status endpoint could mark a finding
-- resolved/monitored/escalated with no accountable assessment at all, bypassing
-- the Assessment stage entirely (ATM-000 section 10, ATM-002 section 8.3).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_findings_outcome_status_coherence'
          AND conrelid = 'findings'::regclass
    ) THEN
        ALTER TABLE findings
            ADD CONSTRAINT chk_findings_outcome_status_coherence
            CHECK (
                status NOT IN ('assessed', 'monitored', 'escalated', 'resolved')
                OR (outcome IS NOT NULL AND assessment_state = 'assessed' AND assessed_at IS NOT NULL)
            );
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_findings_organization_outcome
    ON findings (organization_id, outcome);

CREATE INDEX IF NOT EXISTS idx_findings_organization_assessment_state
    ON findings (organization_id, assessment_state);
