-- ATM-001 M2 — Immutable Knowledge Pack Membership
-- A Knowledge Pack Version is composed by REFERENCES to immutable constituent
-- knowledge versions. This migration adds the membership relation for the one
-- knowledge type that currently possesses a proper immutable version model:
-- task_template_versions.
--
-- Scope:
-- - knowledge_pack_version_task_template_versions: one row per member.
--
-- Composition, not duplication: a membership row references an immutable
-- published version. It never copies template content, so historical pack
-- contents cannot drift when working knowledge is edited.
--
-- Out of scope (explicitly deferred):
-- - Polymorphic membership (item_type / item_version_id).
-- - A generic immutable knowledge-version registry.
-- - knowledge_pack_version_items.
-- - task_template_versions.knowledge_pack_version_id.
-- - Tenant deployment, adoption, snapshot/overlay, synchronisation.
-- - Marketplace distribution and import/export.
-- - Taxonomy membership (no taxonomy version model exists yet).
-- - Any change to M1 publication admission or TaskTemplate.publishVersion().
--
-- Design boundary: task_template_versions stays INDEPENDENT of Knowledge Packs.
-- A task template is published without any pack (M1 contract unchanged), and a
-- published version may subsequently be selected as a member of a
-- pre-publication pack version.
--
-- Idempotent deployment: CREATE IF NOT EXISTS / DROP IF NOT EXISTS throughout.

-- ============================================================
-- knowledge_pack_version_task_template_versions
-- Membership of an immutable task_template_version in a knowledge pack version.
-- ============================================================
CREATE TABLE IF NOT EXISTS knowledge_pack_version_task_template_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    knowledge_pack_version_id INTEGER NOT NULL,
    task_template_version_id INTEGER NOT NULL,
    added_by_user_id INTEGER DEFAULT NULL,
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_kpvtv_pack_version_template_version
        UNIQUE (knowledge_pack_version_id, task_template_version_id),
    -- RESTRICT on both sides: a released pack must never silently lose a member,
    -- and a member must never be removed out from under a released pack.
    CONSTRAINT fk_kpvtv_pack_version
        FOREIGN KEY (knowledge_pack_version_id) REFERENCES knowledge_pack_versions(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_kpvtv_template_version
        FOREIGN KEY (task_template_version_id) REFERENCES task_template_versions(id)
        ON DELETE RESTRICT,
    -- RESTRICT rather than SET NULL: inclusion in a pack is governed historical
    -- attribution, so it must not silently disappear when a user row is removed.
    CONSTRAINT fk_kpvtv_added_by_user
        FOREIGN KEY (added_by_user_id) REFERENCES users(id)
        ON DELETE RESTRICT
);

-- The UNIQUE constraint already provides a leading index on
-- knowledge_pack_version_id. The reverse lookup ("which packs contain this
-- version?") and the RESTRICT check on the referenced version side are not
-- covered, so index that column explicitly.
CREATE INDEX IF NOT EXISTS idx_kpvtv_template_version_id
    ON knowledge_pack_version_task_template_versions (task_template_version_id);

-- ============================================================
-- Membership mutability guard
-- Membership may only be composed while the pack version is still being
-- prepared. Once a pack version is released its membership is historical fact.
--
-- INSERT  allowed while parent lifecycle_state IN (draft, under_review, approved)
--         rejected once the parent is published / superseded / retired
-- UPDATE  always rejected: membership is never retargeted or rewritten
-- DELETE  allowed while parent lifecycle_state IN (draft, under_review, approved)
--         rejected once the parent is published / superseded / retired
--
-- This mirrors the existing immutability guard conventions in migration 009
-- (immutable_version_update_check / immutable_version_delete_check) rather than
-- introducing a generic trigger framework.
-- ============================================================
CREATE OR REPLACE FUNCTION knowledge_pack_membership_guard()
RETURNS TRIGGER AS $$
DECLARE
    parent_lifecycle TEXT;
    parent_version_id INTEGER;
BEGIN
    -- Membership is immutable in the strict sense: it may never be retargeted.
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'knowledge_pack_version_task_template_versions rows are immutable and cannot be updated'
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    IF TG_OP = 'DELETE' THEN
        parent_version_id := OLD.knowledge_pack_version_id;
    ELSE
        parent_version_id := NEW.knowledge_pack_version_id;
    END IF;

    SELECT lifecycle_state INTO parent_lifecycle
    FROM knowledge_pack_versions
    WHERE id = parent_version_id;

    -- A non-existent parent is left to the foreign key to report, so native
    -- referential-integrity semantics produce the canonical FK violation.
    IF parent_lifecycle IS NULL THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;

    IF parent_lifecycle NOT IN ('draft', 'under_review', 'approved') THEN
        RAISE EXCEPTION 'cannot % knowledge pack membership while knowledge_pack_version % is %; membership is frozen once a pack version is released',
            lower(TG_OP), parent_version_id, parent_lifecycle
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop and recreate triggers so the migration stays idempotent.
DROP TRIGGER IF EXISTS trg_kpvtv_membership_guard_insert
    ON knowledge_pack_version_task_template_versions;
DROP TRIGGER IF EXISTS trg_kpvtv_membership_guard_update
    ON knowledge_pack_version_task_template_versions;
DROP TRIGGER IF EXISTS trg_kpvtv_membership_guard_delete
    ON knowledge_pack_version_task_template_versions;

CREATE TRIGGER trg_kpvtv_membership_guard_insert
    BEFORE INSERT ON knowledge_pack_version_task_template_versions
    FOR EACH ROW
    EXECUTE FUNCTION knowledge_pack_membership_guard();

CREATE TRIGGER trg_kpvtv_membership_guard_update
    BEFORE UPDATE ON knowledge_pack_version_task_template_versions
    FOR EACH ROW
    EXECUTE FUNCTION knowledge_pack_membership_guard();

CREATE TRIGGER trg_kpvtv_membership_guard_delete
    BEFORE DELETE ON knowledge_pack_version_task_template_versions
    FOR EACH ROW
    EXECUTE FUNCTION knowledge_pack_membership_guard();
