-- =====================================================
-- ATM-001 M5R.3B — External Classification Foundation
--
-- WHY THIS MIGRATION EXISTS
--
-- The approved standards-crosswalk architecture (see
-- docs/architecture/ATM-001-M5R3-Standards-Crosswalk-Architecture-Decision.md,
-- Option C, APPROVED) separates three things the legacy model conflated:
--
--   1. Atiman canonical equipment identity  -> equipment_categories / _classes / _types
--   2. The external authority and the exact edition that defines a concept
--                                           -> knowledge_sources / knowledge_source_versions
--   3. The governed relationship between them -> NOT built yet (M5R.3C)
--
-- M5R.3A proved item 2 already exists and needs no schema change, so no second
-- authority registry is created here and no authority metadata is duplicated.
--
-- This migration adds the ONE object the crosswalk cannot be built without:
-- the identity of an external concept as defined by ONE exact authority edition.
-- "This edition defines a concept with code C" is a fact about provenance. It is
-- NOT a claim that any Atiman equipment type maps to C, and the existence of a
-- row here never implies one.
--
-- Scope (deliberately minimal — one table, one coherence trigger):
--
--   external_classification
--       An external concept belonging to exactly one knowledge_source_version.
--       Every row MUST identify the edition that defines it.
--
--   trg_external_classification_edition_coherence
--       Fixes the defining edition and the identity code for the life of the
--       row, so an external edition change cannot silently rewrite what the row
--       means.
--
-- Out of scope (explicitly deferred, so that this migration cannot imply them):
--
--   - equipment_type_external_classification (the governed crosswalk) and its
--     coherence/attribution CHECKs, immutability/deletion/supersession triggers,
--     partial unique indexes and global-scope trigger ........... M5R.3C
--   - crosswalk evidence (exactly-one-subject) .................. M5R.3D
--   - review/publication state for classifications. `is_active` is the
--     availability of a reference concept, not governance of a mapping.
--     Crosswalk governance belongs to the crosswalk (M5R.3C).
--   - external hierarchy STRUCTURE (parent_id, tree, closure table, ontology).
--     The approved decision is EXTERNAL HIERARCHY STRUCTURAL MODELLING DEFERRED;
--     classification_path is an optional informative string only.
--   - any populated external classification data. This migration creates
--     STRUCTURE, not a standards database. No licensed content is involved.
--
-- Not in scope and not touched: any Atiman taxonomy object, any legacy
-- iso_* reference column (FALSE_PROVENANCE_REMEDIATION_REQUIRED remains
-- separate), any 282/60-type reconciliation, any customer alias layer.
--
-- Idempotent deployment: CREATE IF NOT EXISTS / DROP IF NOT EXISTS throughout,
-- and CREATE OR REPLACE for the trigger function. Safe to re-run.
-- =====================================================

-- ============================================================
-- external_classification: an external concept defined by ONE authority edition
-- ============================================================
CREATE TABLE IF NOT EXISTS external_classification (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    -- The EDITION that defines this concept, not merely the authority. Edition
    -- identity is mandatory: the same code in two editions is two distinct
    -- concepts and must be separately representable.
    knowledge_source_version_id INTEGER NOT NULL,
    classification_code VARCHAR(100) NOT NULL,
    classification_label VARCHAR(500) NOT NULL,
    -- Optional informative path for hierarchical codes. Deliberately NOT a
    -- modelled hierarchy: no parent_id, no closure table, no structural
    -- navigation. Atiman must not become a mirrored standards database.
    classification_path VARCHAR(500) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    -- One concept per code WITHIN one edition. Deliberately scoped to the
    -- edition: the same code MAY legitimately appear in a different edition.
    -- The composite index also serves lookup by knowledge_source_version_id.
    CONSTRAINT uq_external_classification_version_code
        UNIQUE (knowledge_source_version_id, classification_code),
    -- Edition provenance is immutable and delete-protected (011). RESTRICT, not
    -- CASCADE: deleting an authority edition must never silently destroy
    -- governed reference knowledge.
    CONSTRAINT fk_external_classification_source_version
        FOREIGN KEY (knowledge_source_version_id) REFERENCES knowledge_source_versions(id) ON DELETE RESTRICT
);

-- ============================================================
-- Edition coherence: the defining edition and the identity code are fixed for
-- the life of the row.
--
-- Rationale: an external classification IS its (edition, code) identity.
-- Allowing either to be silently rewritten would retroactively change what every
-- later crosswalk row referencing it meant — the architecture's requirement
-- that "an external edition change must not silently rewrite history". When an
-- edition renames or re-scopes a concept, the answer is a NEW classification
-- row for the NEW edition, exactly as M5R.3 §J describes.
--
-- This mirrors the repository's existing knowledge_sources_identity_lock_check
-- idiom (migration 011): stable identity is locked by trigger, not by hope.
--
-- Deliberately NOT locked: classification_label, classification_path,
-- description and is_active. Those are display and availability, not identity.
-- ============================================================
CREATE OR REPLACE FUNCTION external_classification_edition_coherence_check()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.knowledge_source_version_id IS DISTINCT FROM NEW.knowledge_source_version_id THEN
        RAISE EXCEPTION 'external_classification % knowledge_source_version_id cannot change; an external classification is defined by exactly one authority edition', OLD.id
            USING ERRCODE = 'check_violation';
    END IF;

    IF OLD.classification_code IS DISTINCT FROM NEW.classification_code THEN
        RAISE EXCEPTION 'external_classification % classification_code cannot change; external concept identity within an edition is fixed', OLD.id
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_external_classification_edition_coherence
    ON external_classification;

CREATE TRIGGER trg_external_classification_edition_coherence
    BEFORE UPDATE ON external_classification
    FOR EACH ROW
    EXECUTE FUNCTION external_classification_edition_coherence_check();
