-- =====================================================
-- ATM-001 M5R.3C — Governed Equipment-Type / External-Classification Crosswalk
--
-- WHY THIS MIGRATION EXISTS
--
-- The approved standards-crosswalk architecture (see
-- docs/architecture/ATM-001-M5R3-Standards-Crosswalk-Architecture-Decision.md,
-- Option C, APPROVED) establishes that Atiman owns canonical equipment identity
-- (Category -> Class -> Type) while an external authority edition defines its own
-- concepts. Migration 016 built the external CONCEPT. This migration builds the
-- governed RELATIONSHIP between the two — one row = one governed proposition:
--
--   "Atiman equipment type T is related to external concept C, as defined by
--    authority edition E, through relationship R, for applicability A."
--   or, instead:
--   "T was investigated against edition E and no defensible direct mapping exists."
--
-- THE THREE STATES THIS MODEL MUST KEEP DISTINCT (M5R.3 §H.0, NORMATIVE)
--
--   1. NEVER INVESTIGATED  -> NO ROW. Absence is not a finding, and no
--                             placeholder row is ever created to represent
--                             research activity or partial progress.
--   2. MAPPED OUTCOME      -> row, mapping_outcome IN ('DIRECT_EQUIVALENT',
--                             'RELATED_TO','BROADER_THAN','NARROWER_THAN'),
--                             external_classification_id NOT NULL, and the
--                             classification MUST belong to the crosswalk's own
--                             knowledge_source_version_id.
--   3. NO_DIRECT_MAPPING   -> row, mapping_outcome='NO_DIRECT_MAPPING',
--                             external_classification_id NULL, and the exact
--                             investigated edition still recorded. This is a
--                             POSITIVE, evidenced conclusion — never equivalent
--                             to "never investigated", "unknown", or NULL.
--
-- `review_state` answers a different question again — "is this proposition
-- governed?" — and is deliberately a separate dimension, so that
-- APPROVED + NO_DIRECT_MAPPING is a first-class positive finding rather than a
-- pseudo-state. `approved` is the terminal governed state for a crosswalk; there
-- is NO separate publication state for V1 (§U / §AI item 2).
--
-- Supersession is governed too (refined by ATM-001 M5R.3C-R1): setting the
-- supersession pointer decides which governed knowledge is current, so an
-- APPROVED crosswalk may only be superseded by an APPROVED successor about the
-- SAME equipment type. A governed conclusion therefore cannot be deactivated by
-- ungoverned or unrelated knowledge. See Trigger 5/5 below.
--
-- WHAT THIS MIGRATION DELIBERATELY DOES NOT DO
--
--   - No crosswalk EVIDENCE association. Exactly-one-subject evidence is a
--     separate slice (M5R.3D); the existing provenance evidence tables are not
--     altered to accept crosswalk subjects.
--   - No service, model, controller, route, UI or permission. `approved`
--     currently requires the ADR's attribution columns, not an application code
--     path; read/lifecycle operations are M5R.3E.
--   - No AI mechanism. `ai_assisted` / `ai_assistance_detail` exist only so that
--     an AI-proposed row stays distinguishable from human-approved truth; an AI
--     suggestion still requires an accountable human approver (§T).
--   - No standards content and no populated rows. Structure only.
--   - No external hierarchy structure, no ontology, no customer alias layer, no
--     taxonomy change. Atiman canonical identity is referenced, never modified.
--   - No use of the legacy iso_* reference columns.
--     FALSE_PROVENANCE_REMEDIATION_REQUIRED remains a separate future task.
--
-- GLOBAL-SOURCE INVARIANT (§R.1 — the M5R.3B non-claim, now closed)
--
-- M5R.3B deliberately allowed an external_classification to exist under a
-- tenant-scoped edition, because the ADR assigns the mandatory global-source
-- guard to the crosswalk/evidence layer. That guard is implemented HERE. Every
-- crosswalk row must resolve, through knowledge_source_versions -> knowledge_sources,
-- to a GLOBAL source (organization_id IS NULL). Combined with edition coherence,
-- a tenant-scoped classification is therefore unreachable from the global
-- crosswalk: its edition is not global, so no crosswalk row may cite it.
-- Customer-specific classification systems belong to a separate tenant-scoped
-- alias architecture, which is NOT implemented here.
--
-- Idempotent deployment: CREATE IF NOT EXISTS / DROP IF NOT EXISTS / CREATE OR
-- REPLACE throughout. Safe to re-run.
-- =====================================================

-- ============================================================
-- equipment_type_external_classification: the governed crosswalk
-- ============================================================
CREATE TABLE IF NOT EXISTS equipment_type_external_classification (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    -- Atiman canonical identity. Referenced, never owned: the relationship is
    -- owned by the Atiman equipment identity, not by any external system.
    equipment_type_id INTEGER NOT NULL,
    -- The EXACT authority edition that was investigated. Mandatory on every row,
    -- including NO_DIRECT_MAPPING, so "which edition did we read" can never be
    -- absent (M5R.3 §H.0 / §H.1 design decision 2).
    knowledge_source_version_id INTEGER NOT NULL,
    -- NULL ONLY for NO_DIRECT_MAPPING. Never a fabricated classification.
    external_classification_id INTEGER DEFAULT NULL,
    -- Redundant by construction with mapping_outcome when mapped (the coherence
    -- CHECK below ties them together). Retained because the approved uniqueness
    -- rule (§W.1) is expressed over it.
    relationship VARCHAR(30) DEFAULT NULL
        CONSTRAINT chk_equipment_type_external_classification_relationship
        CHECK (relationship IN ('DIRECT_EQUIVALENT', 'RELATED_TO', 'BROADER_THAN', 'NARROWER_THAN')),
    -- Governance status of the proposition — NOT approval state of the finding.
    review_state VARCHAR(20) NOT NULL DEFAULT 'draft'
        CONSTRAINT chk_equipment_type_external_classification_review_state
        CHECK (review_state IN ('draft', 'under_review', 'approved', 'rejected')),
    -- What was concluded. Deliberately a different column from review_state.
    mapping_outcome VARCHAR(30) NOT NULL
        CONSTRAINT chk_equipment_type_external_classification_mapping_outcome
        CHECK (mapping_outcome IN ('DIRECT_EQUIVALENT', 'RELATED_TO', 'BROADER_THAN',
                                   'NARROWER_THAN', 'NO_DIRECT_MAPPING')),
    -- Structured applicability for V1 is INDUSTRY ONLY (§R / §AI item 3). No
    -- jurisdiction, lifecycle phase, OEM, site, service or customer dimension,
    -- and no free-form context JSON.
    applicability_industry_id INTEGER DEFAULT NULL,
    applicability_note TEXT DEFAULT NULL,
    confidence_level VARCHAR(50) NOT NULL DEFAULT 'provisional'
        CONSTRAINT chk_equipment_type_external_classification_confidence
        CHECK (confidence_level IN ('established', 'provisional', 'experimental', 'uncertain')),
    supporting_role VARCHAR(50) NOT NULL DEFAULT 'supporting'
        CONSTRAINT chk_equipment_type_external_classification_role
        CHECK (supporting_role IN ('primary', 'supporting')),
    proposed_by_user_id INTEGER DEFAULT NULL,
    reviewed_by_user_id INTEGER DEFAULT NULL,
    reviewed_at TIMESTAMPTZ DEFAULT NULL,
    approved_by_user_id INTEGER DEFAULT NULL,
    approved_at TIMESTAMPTZ DEFAULT NULL,
    -- Distinguishes an AI-assisted proposal from human-approved truth. AI may
    -- never populate approved_by_user_id (enforced by the attribution CHECK).
    ai_assisted BOOLEAN NOT NULL DEFAULT FALSE,
    ai_assistance_detail JSONB DEFAULT NULL,
    -- Supersession is a NEW row plus this back-link. Never an in-place rewrite.
    superseded_by_crosswalk_id INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),

    -- NORMATIVE outcome/classification coherence (M5R.3 §H.0, OWNER-approved):
    -- a mapped outcome without a classification, and a NO_DIRECT_MAPPING carrying
    -- one, are both unrepresentable. So is a persisted row that is neither a
    -- proposition about a classification nor an explicit NDM conclusion.
    CONSTRAINT chk_equipment_type_external_classification_outcome_coherent
        CHECK (
            (mapping_outcome = 'NO_DIRECT_MAPPING'
                 AND external_classification_id IS NULL AND relationship IS NULL)
            OR
            (mapping_outcome <> 'NO_DIRECT_MAPPING'
                 AND external_classification_id IS NOT NULL AND relationship = mapping_outcome)
        ),

    -- Governance completeness: an approved row carries full accountable human
    -- attribution, so an unattributed governed row is unrepresentable.
    -- (ADR §W names this `chk_..._approved_requires_attribution`; that spelled-out
    --  suffix exceeds PostgreSQL's 63-byte identifier limit, and PostgreSQL
    --  TRUNCATES silently rather than failing, so the name is shortened
    --  deliberately here instead of being cut off mid-word.)
    CONSTRAINT chk_equipment_type_external_classification_approved_attributed
        CHECK (
            review_state <> 'approved' OR (
                reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL AND
                approved_by_user_id IS NOT NULL AND approved_at IS NOT NULL
            )
        ),

    CONSTRAINT chk_equipment_type_external_classification_no_self_supersession
        CHECK (superseded_by_crosswalk_id IS NULL OR superseded_by_crosswalk_id <> id),

    -- RESTRICT throughout: governed mapping history must never disappear through
    -- a cascading delete of the taxonomy, the edition, or the external concept.
    CONSTRAINT fk_equipment_type_external_classification_equipment_type
        FOREIGN KEY (equipment_type_id) REFERENCES equipment_types(id) ON DELETE RESTRICT,
    CONSTRAINT fk_equipment_type_external_classification_source_version
        FOREIGN KEY (knowledge_source_version_id) REFERENCES knowledge_source_versions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_equipment_type_external_classification_external_class
        FOREIGN KEY (external_classification_id) REFERENCES external_classification(id) ON DELETE RESTRICT,
    CONSTRAINT fk_equipment_type_external_classification_industry
        FOREIGN KEY (applicability_industry_id) REFERENCES industries(id) ON DELETE SET NULL,
    CONSTRAINT fk_equipment_type_external_classification_superseded_by
        FOREIGN KEY (superseded_by_crosswalk_id) REFERENCES equipment_type_external_classification(id) ON DELETE SET NULL
);

-- ============================================================
-- Uniqueness (M5R.3 §W.1) — deliberately PARTIAL.
--
-- Only simultaneously ACTIVE and APPROVED rows are constrained. draft,
-- under_review, rejected and superseded rows may coexist freely, so competing
-- proposals and full history remain representable. Uniqueness is never achieved
-- by deleting old knowledge.
-- ============================================================

-- At most one active approved mapping per (type, classification, relationship).
CREATE UNIQUE INDEX IF NOT EXISTS uq_equipment_type_external_classification_active_mapping
    ON equipment_type_external_classification
       (equipment_type_id, external_classification_id, relationship)
    WHERE review_state = 'approved'
      AND superseded_by_crosswalk_id IS NULL
      AND external_classification_id IS NOT NULL;

-- At most one active approved NO_DIRECT_MAPPING per (type, edition).
-- `ndm` is the ADR's own abbreviation for NO_DIRECT_MAPPING (§H.3, §O); the
-- spelled-out suffix would exceed the 63-byte identifier limit and be truncated.
CREATE UNIQUE INDEX IF NOT EXISTS uq_equipment_type_external_classification_active_ndm
    ON equipment_type_external_classification
       (equipment_type_id, knowledge_source_version_id)
    WHERE review_state = 'approved'
      AND superseded_by_crosswalk_id IS NULL
      AND mapping_outcome = 'NO_DIRECT_MAPPING';

-- ============================================================
-- Indexes for actual read paths (M5R.3 §W.2). The FK columns are indexed
-- because PostgreSQL does not index foreign keys automatically.
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_equipment_type_external_classification_type_review
    ON equipment_type_external_classification (equipment_type_id, review_state);

CREATE INDEX IF NOT EXISTS idx_equipment_type_external_classification_external_class
    ON equipment_type_external_classification (external_classification_id);

CREATE INDEX IF NOT EXISTS idx_equipment_type_external_classification_source_version
    ON equipment_type_external_classification (knowledge_source_version_id);

CREATE INDEX IF NOT EXISTS idx_equipment_type_external_classification_superseded_by
    ON equipment_type_external_classification (superseded_by_crosswalk_id);

-- ============================================================
-- Trigger 1/5 — Immutability (M5R.3 §Q, §W.3.1)
--
-- Once approved, a crosswalk row is frozen except its supersession pointer. A
-- governed conclusion may not be silently rewritten: changing the type, the
-- investigated edition, the classification, the outcome, the applicability, the
-- attribution or the review state of an approved row is refused outright.
--
-- Implemented as a whole-row comparison so that a column added later cannot be
-- left silently mutable — the rule is "nothing but superseded_by_crosswalk_id",
-- not a hand-maintained list that could drift from the table definition.
-- ============================================================
CREATE OR REPLACE FUNCTION crosswalk_approved_immutability_check()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.review_state = 'approved' THEN
        IF (to_jsonb(NEW) - 'superseded_by_crosswalk_id')
           IS DISTINCT FROM
           (to_jsonb(OLD) - 'superseded_by_crosswalk_id') THEN
            RAISE EXCEPTION 'approved crosswalk % is immutable except its supersession pointer', OLD.id
                USING ERRCODE = 'insufficient_privilege';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_equipment_type_external_classification_immutable
    ON equipment_type_external_classification;

CREATE TRIGGER trg_equipment_type_external_classification_immutable
    BEFORE UPDATE ON equipment_type_external_classification
    FOR EACH ROW
    EXECUTE FUNCTION crosswalk_approved_immutability_check();

-- ============================================================
-- Trigger 2/5 — Delete protection (M5R.3 §Q, §W.3.2)
--
-- Hard delete is permitted ONLY while a row is still a draft proposal. Once
-- submitted, reviewed, approved or rejected, the row is governed knowledge and
-- is retained: "this mapping was considered and refused" must stay visible, or
-- the same proposal can be re-litigated with no record that it was declined.
-- ============================================================
CREATE OR REPLACE FUNCTION crosswalk_delete_guard()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.review_state <> 'draft' THEN
        RAISE EXCEPTION 'crosswalk % is % and cannot be deleted; only draft proposals are deletable', OLD.id, OLD.review_state
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_equipment_type_external_classification_delete_guard
    ON equipment_type_external_classification;

CREATE TRIGGER trg_equipment_type_external_classification_delete_guard
    BEFORE DELETE ON equipment_type_external_classification
    FOR EACH ROW
    EXECUTE FUNCTION crosswalk_delete_guard();

-- ============================================================
-- Trigger 3/5 — Edition coherence (M5R.3 §W.3.3)
--
-- A mapped crosswalk must never claim "we mapped against edition A" while
-- referencing a classification that belongs to edition B. The primary defence
-- for "an external edition change must not silently rewrite history": the
-- classification and the crosswalk must name the SAME edition.
-- ============================================================
CREATE OR REPLACE FUNCTION crosswalk_edition_coherence_check()
RETURNS TRIGGER AS $$
DECLARE
    classification_version_id INTEGER;
BEGIN
    IF NEW.external_classification_id IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT knowledge_source_version_id INTO classification_version_id
    FROM external_classification
    WHERE id = NEW.external_classification_id;

    IF classification_version_id IS NULL THEN
        RAISE EXCEPTION 'external_classification % does not exist', NEW.external_classification_id
            USING ERRCODE = 'foreign_key_violation';
    END IF;

    IF classification_version_id IS DISTINCT FROM NEW.knowledge_source_version_id THEN
        RAISE EXCEPTION 'crosswalk investigated edition % but external_classification % belongs to edition %; a mapping may not cite a concept from a different edition', NEW.knowledge_source_version_id, NEW.external_classification_id, classification_version_id
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_equipment_type_external_classification_edition_coherence
    ON equipment_type_external_classification;

CREATE TRIGGER trg_equipment_type_external_classification_edition_coherence
    BEFORE INSERT OR UPDATE ON equipment_type_external_classification
    FOR EACH ROW
    EXECUTE FUNCTION crosswalk_edition_coherence_check();

-- ============================================================
-- Trigger 4/5 — Global-source enforcement (M5R.3 §R.1) — MANDATORY
--
-- A global crosswalk must never derive authority from a tenant-scoped knowledge
-- source, or customer terminology leaks into global Atiman knowledge. Resolving
-- knowledge_source_version -> knowledge_source is the only accepted proof of
-- global scope. This mirrors the existing provenance_tenant_scope_check idiom
-- (migration 011) and closes the M5R.3B non-claim.
-- ============================================================
CREATE OR REPLACE FUNCTION crosswalk_global_scope_check()
RETURNS TRIGGER AS $$
DECLARE
    source_org_id INTEGER;
BEGIN
    SELECT s.organization_id INTO source_org_id
    FROM knowledge_source_versions v
    JOIN knowledge_sources s ON s.id = v.knowledge_source_id
    WHERE v.id = NEW.knowledge_source_version_id;

    -- A missing version is left to the foreign key, which reports it precisely.
    IF source_org_id IS NOT NULL THEN
        RAISE EXCEPTION 'crosswalk % may not derive authority from tenant-scoped knowledge_source (organization_id %)', NEW.id, source_org_id
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_equipment_type_external_classification_global_scope
    ON equipment_type_external_classification;

CREATE TRIGGER trg_equipment_type_external_classification_global_scope
    BEFORE INSERT OR UPDATE ON equipment_type_external_classification
    FOR EACH ROW
    EXECUTE FUNCTION crosswalk_global_scope_check();

-- ============================================================
-- Trigger 5/5 — Supersession validity (M5R.3 §Q, §W.3.5; refined by M5R.3C-R1)
--
-- Supersession is a new row plus a back-link, never an in-place rewrite.
--
-- Setting the pointer decides which governed knowledge is CURRENT, so a governed
-- predecessor may not be deactivated by ungoverned or unrelated knowledge. When
-- the row being superseded is APPROVED, its successor must therefore also be
-- APPROVED, and must concern the SAME Atiman equipment type. The successor may
-- legitimately carry another edition, another external classification, another
-- relationship, another outcome or another applicability — those are precisely
-- the reasons a proposition is superseded (M5R.3 §J: a new edition produces a
-- new row for the same type). Requiring the successor to differ in those fields
-- would be wrong; requiring the same SUBJECT and the same GOVERNANCE is the
-- invariant that matters.
--
-- Consequences of the refinement:
--   * approved -> draft / under_review / rejected successor is impossible;
--   * approved -> successor about a different equipment type is impossible;
--   * because the delete guard permits only DRAFT rows to be deleted, an
--     APPROVED successor can never be deleted, so the ON DELETE SET NULL
--     pointer can never fire for it and a governed predecessor can never be
--     silently reactivated that way;
--   * an approved row cannot be superseded by a literally identical proposition,
--     because two identical active approved propositions cannot both exist
--     (the partial unique indexes) and ordering cannot resolve that deadlock.
--     Superseding with an identical proposition carries no meaning in any case.
--
-- Self-reference (also a CHECK) and cycles remain refused.
-- ============================================================
CREATE OR REPLACE FUNCTION crosswalk_supersession_check()
RETURNS TRIGGER AS $$
DECLARE
    next_id INTEGER;
    successor_review_state VARCHAR(20);
    successor_equipment_type_id INTEGER;
    visited INTEGER[];
BEGIN
    IF NEW.superseded_by_crosswalk_id IS NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.id = NEW.superseded_by_crosswalk_id THEN
        RAISE EXCEPTION 'crosswalk % cannot supersede itself', NEW.id
            USING ERRCODE = 'check_violation';
    END IF;

    SELECT review_state, equipment_type_id
    INTO successor_review_state, successor_equipment_type_id
    FROM equipment_type_external_classification
    WHERE id = NEW.superseded_by_crosswalk_id;

    -- review_state is NOT NULL, so a NULL here means the successor does not exist.
    IF successor_review_state IS NULL THEN
        RAISE EXCEPTION 'superseded_by_crosswalk_id must reference an existing crosswalk row'
            USING ERRCODE = 'foreign_key_violation';
    END IF;

    -- Only a GOVERNED predecessor confers the governance meaning "no longer
    -- current", so only then must the successor itself be governed, and about
    -- the same subject.
    IF NEW.review_state = 'approved' THEN
        IF successor_review_state <> 'approved' THEN
            RAISE EXCEPTION 'approved crosswalk % may only be superseded by an approved successor; successor % is %', NEW.id, NEW.superseded_by_crosswalk_id, successor_review_state
                USING ERRCODE = 'check_violation';
        END IF;

        IF successor_equipment_type_id IS DISTINCT FROM NEW.equipment_type_id THEN
            RAISE EXCEPTION 'approved crosswalk % may only be superseded by a successor for the same equipment type; successor % concerns equipment type %', NEW.id, NEW.superseded_by_crosswalk_id, successor_equipment_type_id
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    -- Cycle detection: follow the successor chain from the proposed successor.
    next_id := NEW.superseded_by_crosswalk_id;
    visited := ARRAY[NEW.id];
    LOOP
        IF next_id = ANY(visited) THEN
            RAISE EXCEPTION 'supersession assignment would create a cycle involving crosswalk %', NEW.id
                USING ERRCODE = 'check_violation';
        END IF;
        visited := array_append(visited, next_id);
        SELECT superseded_by_crosswalk_id INTO next_id
        FROM equipment_type_external_classification
        WHERE id = next_id;
        EXIT WHEN next_id IS NULL;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_equipment_type_external_classification_supersession
    ON equipment_type_external_classification;

CREATE TRIGGER trg_equipment_type_external_classification_supersession
    BEFORE INSERT OR UPDATE ON equipment_type_external_classification
    FOR EACH ROW
    EXECUTE FUNCTION crosswalk_supersession_check();
