-- ATM-001 M6.3 — Governed Knowledge Foundation
--
-- Converts the ratified M6.2/M6.3 maintenance-knowledge architecture into schema
-- and governance mechanism. Maintenance Knowledge and Inspection Knowledge are
-- constitutionally distinct Knowledge Foundation domains; they share this one
-- governed knowledge-definition substrate and are distinguished by an explicit,
-- immutable knowledge type that is frozen into each immutable published version.
--
-- Scope (ratified M6.3 minimum):
--   * governed knowledge-type vocabulary + explicit type on definition and version
--   * governed task-family vocabulary (seven ratified families)
--   * governed maintenance-strategy representation (five ratified strategies)
--   * working and frozen Equipment-Type applicability junctions
--   * structured trigger-recommendation model (mechanism / criterion / magnitude /
--     basis / explicit no-fixed-interval) that cannot express a scheduled date
--   * explicit knowledge scope (shared / customer; marketplace non-assignable)
--   * explicit content origin with a fail-closed legacy-corpus manifest
--
-- Explicitly NOT in scope: scheduling, due dates, work orders, labour, materials,
-- inventory, procurement, cost or permit functionality; per-control safety
-- provenance; procedure terminology; a generic knowledge registry; a separate
-- inspection governance stack; marketplace commerce; any AI feature.
--
-- Idempotency: scripts/migrate-postgres.js reapplies every migration on every run
-- and keeps no applied-migrations ledger, so this file must be safe to execute
-- repeatedly. All DDL is guarded (CREATE ... IF NOT EXISTS / ADD COLUMN IF NOT
-- EXISTS / guarded DO blocks / DROP TRIGGER IF EXISTS before CREATE), all seeds
-- use ON CONFLICT DO NOTHING, and every backfill is written so that a second run
-- matches zero rows.
--
-- Forward-only: there is no down-migration. Every change here is additive and no
-- existing constraint is dropped or weakened.
--
-- Legacy manifest provenance: the identity set below is frozen from the accepted
-- M6.1 reconciliation artifact
--   docs/research/m6r1/maintenance-procedure-reconciliation.jsonl
-- (846 records, sha256 prefix 8e0e32e522b6c519). It is an explicit manifest, not a
-- timestamp or a heuristic predicate. A future revision of the corpus requires a
-- NEW forward migration; this file must never be edited to accommodate one.

-- ===========================================================================
-- PART 1 — governed knowledge vocabularies
-- ===========================================================================

-- Knowledge type: which constitutional Knowledge Foundation domain this governed
-- definition belongs to. A reference table, not a CHECK constraint, because the
-- Constitution enumerates further domains and adding one must be a governed data
-- action rather than a schema migration.
CREATE TABLE IF NOT EXISTS knowledge_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_code VARCHAR(50) NOT NULL,
    type_name VARCHAR(200) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_knowledge_types_type_code UNIQUE (type_code)
);

-- Only the semantic types this substrate currently carries are seeded. Further
-- constitutional domains are added as governed data when they adopt this substrate.
INSERT INTO knowledge_types (type_code, type_name, description) VALUES
    ('MAINTENANCE_PROCEDURE', 'Maintenance Procedure',
     'Knowledge describing how assets are maintained: governed maintenance procedures, technical actions, acceptance criteria, maintenance strategy, safety guidance and recommended maintenance triggers.'),
    ('INSPECTION_TEMPLATE', 'Inspection Template',
     'Knowledge describing what condition evidence operators or inspectors should observe, check, measure or assess.')
ON CONFLICT (type_code) DO NOTHING;

-- Task family: what kind of action the knowledge prescribes. Orthogonal to
-- knowledge type and never inferred from it. A reference table because ATM-013C2
-- §1.2 explicitly permits additional families where engineering evidence supports
-- them, so growth must be a data action.
CREATE TABLE IF NOT EXISTS task_families (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    family_code VARCHAR(50) NOT NULL,
    family_name VARCHAR(200) NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_task_families_family_code UNIQUE (family_code)
);

INSERT INTO task_families (family_code, family_name, description, sort_order) VALUES
    ('inspect',        'Inspect',        'Observe, detect and capture condition evidence.', 1),
    ('verify_safety',  'Verify Safety',  'Confirm protective devices, isolation, guarding, alarms and emergency systems.', 2),
    ('test_measure',   'Test / Measure', 'Quantify performance, calibrate, validate function and record readings.', 3),
    ('lubricate',      'Lubricate',      'Apply or check lubricant condition.', 4),
    ('clean',          'Clean',          'Remove contamination or restore cleanliness.', 5),
    ('adjust',         'Adjust',         'Restore setpoints, alignment or tension.', 6),
    ('replace',        'Replace',        'Exchange worn or consumable parts.', 7)
ON CONFLICT (family_code) DO NOTHING;

-- ===========================================================================
-- PART 2 — Equipment-Type applicability junctions
-- ===========================================================================
-- Applicability is an enumerated set of immutable Equipment Type identities.
-- No class, category, subunit, maintainable-item or asset inference exists, and
-- no tenant override semantics are introduced.

CREATE TABLE IF NOT EXISTS task_template_equipment_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_id INTEGER NOT NULL,
    equipment_type_id INTEGER NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    added_by_user_id INTEGER DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_ttet_template_equipment_type UNIQUE (task_template_id, equipment_type_id)
);

-- Exactly one primary anchor per governed definition.
CREATE UNIQUE INDEX IF NOT EXISTS uq_ttet_one_primary_per_template
    ON task_template_equipment_types (task_template_id)
    WHERE is_primary;

CREATE TABLE IF NOT EXISTS task_template_version_equipment_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_template_version_id INTEGER NOT NULL,
    equipment_type_id INTEGER NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_ttvet_version_equipment_type UNIQUE (task_template_version_id, equipment_type_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_ttvet_one_primary_per_version
    ON task_template_version_equipment_types (task_template_version_id)
    WHERE is_primary;

-- ===========================================================================
-- PART 3 — governed columns on the working definition
-- ===========================================================================
-- knowledge_scope and content_origin deliberately carry NO default: an omitted
-- scope must not silently become an ownership classification, and an omitted
-- origin must not silently assert authorship.

ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS knowledge_type_id INTEGER DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS task_family_id INTEGER DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS maintenance_strategy VARCHAR(50) DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS trigger_mechanism VARCHAR(50) DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS trigger_condition_parameter VARCHAR(200) DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS trigger_condition_operator VARCHAR(20) DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS trigger_condition_value NUMERIC(18,6) DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS trigger_condition_unit VARCHAR(50) DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS trigger_condition_context TEXT DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS trigger_event_description VARCHAR(255) DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS trigger_basis_source_version_id INTEGER DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS knowledge_scope VARCHAR(20);
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS content_origin VARCHAR(20);
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS legacy_clearance_by_user_id INTEGER DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS legacy_clearance_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS legacy_clearance_rationale TEXT DEFAULT NULL;

-- frequency_interval is deprecated for governed knowledge but still carries a stale
-- DEFAULT of 1 from migration 003. Left in place it would make every new governed row
-- violate chk_task_templates_no_scheduling_on_governed without the author doing anything
-- wrong, so the default is removed. The column and all existing values are preserved.
ALTER TABLE task_templates ALTER COLUMN frequency_interval DROP DEFAULT;

-- ===========================================================================
-- PART 4 — governed columns on the immutable version
-- ===========================================================================
-- Mirrored so that a published version freezes its domain, family, strategy,
-- trigger recommendation and ownership binding. organization_id is included
-- because a frozen 'customer' scope is meaningless without the tenant binding it
-- referred to, and the definition's own organization_id is mutable.

ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS knowledge_type_id INTEGER DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS task_family_id INTEGER DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS maintenance_strategy VARCHAR(50) DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS trigger_mechanism VARCHAR(50) DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS trigger_condition_parameter VARCHAR(200) DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS trigger_condition_operator VARCHAR(20) DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS trigger_condition_value NUMERIC(18,6) DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS trigger_condition_unit VARCHAR(50) DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS trigger_condition_context TEXT DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS trigger_event_description VARCHAR(255) DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS trigger_basis_source_version_id INTEGER DEFAULT NULL;
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS knowledge_scope VARCHAR(20);
ALTER TABLE task_template_versions ADD COLUMN IF NOT EXISTS organization_id INTEGER DEFAULT NULL;

-- ===========================================================================
-- PART 5 — Knowledge Pack ownership scope
-- ===========================================================================

ALTER TABLE knowledge_packs ADD COLUMN IF NOT EXISTS knowledge_scope VARCHAR(20);
ALTER TABLE knowledge_packs ADD COLUMN IF NOT EXISTS organization_id INTEGER DEFAULT NULL;
ALTER TABLE knowledge_pack_versions ADD COLUMN IF NOT EXISTS knowledge_scope VARCHAR(20);

-- ===========================================================================
-- PART 6 — foreign keys
-- ===========================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_templates_knowledge_type'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_knowledge_type
            FOREIGN KEY (knowledge_type_id) REFERENCES knowledge_types(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_templates_task_family'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_task_family
            FOREIGN KEY (task_family_id) REFERENCES task_families(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_templates_trigger_basis_source_version'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_trigger_basis_source_version
            FOREIGN KEY (trigger_basis_source_version_id) REFERENCES knowledge_source_versions(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_templates_legacy_clearance_by_user'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT fk_task_templates_legacy_clearance_by_user
            FOREIGN KEY (legacy_clearance_by_user_id) REFERENCES users(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_template_versions_knowledge_type'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT fk_task_template_versions_knowledge_type
            FOREIGN KEY (knowledge_type_id) REFERENCES knowledge_types(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_template_versions_task_family'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT fk_task_template_versions_task_family
            FOREIGN KEY (task_family_id) REFERENCES task_families(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_template_versions_trigger_basis_source_version'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT fk_task_template_versions_trigger_basis_source_version
            FOREIGN KEY (trigger_basis_source_version_id) REFERENCES knowledge_source_versions(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_task_template_versions_organization'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT fk_task_template_versions_organization
            FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ttet_task_template'
                   AND conrelid = 'task_template_equipment_types'::regclass) THEN
        ALTER TABLE task_template_equipment_types ADD CONSTRAINT fk_ttet_task_template
            FOREIGN KEY (task_template_id) REFERENCES task_templates(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ttet_equipment_type'
                   AND conrelid = 'task_template_equipment_types'::regclass) THEN
        ALTER TABLE task_template_equipment_types ADD CONSTRAINT fk_ttet_equipment_type
            FOREIGN KEY (equipment_type_id) REFERENCES equipment_types(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ttet_added_by_user'
                   AND conrelid = 'task_template_equipment_types'::regclass) THEN
        ALTER TABLE task_template_equipment_types ADD CONSTRAINT fk_ttet_added_by_user
            FOREIGN KEY (added_by_user_id) REFERENCES users(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ttvet_task_template_version'
                   AND conrelid = 'task_template_version_equipment_types'::regclass) THEN
        ALTER TABLE task_template_version_equipment_types ADD CONSTRAINT fk_ttvet_task_template_version
            FOREIGN KEY (task_template_version_id) REFERENCES task_template_versions(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ttvet_equipment_type'
                   AND conrelid = 'task_template_version_equipment_types'::regclass) THEN
        ALTER TABLE task_template_version_equipment_types ADD CONSTRAINT fk_ttvet_equipment_type
            FOREIGN KEY (equipment_type_id) REFERENCES equipment_types(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_knowledge_packs_organization'
                   AND conrelid = 'knowledge_packs'::regclass) THEN
        ALTER TABLE knowledge_packs ADD CONSTRAINT fk_knowledge_packs_organization
            FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
END
$$;

-- ===========================================================================
-- PART 7 — governed-state and consistency constraints
-- ===========================================================================
-- Every requirement is state-conditional on the working record's review_state, or
-- on the version's lifecycle_state_at_publish, so that unclassified drafts and all
-- 846 legacy candidates (which are drafts) remain valid.

DO $$
BEGIN
    -- ---- task_templates: value constraints --------------------------------
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_maintenance_strategy'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_maintenance_strategy
            CHECK (maintenance_strategy IS NULL OR maintenance_strategy IN
                ('preventive','predictive','condition_based','compliance','corrective'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_trigger_mechanism'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_trigger_mechanism
            CHECK (trigger_mechanism IS NULL OR trigger_mechanism IN
                ('calendar','hours_based','condition_based','event','no_fixed_interval'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_frequency_unit_values'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_frequency_unit_values
            CHECK (frequency_unit IS NULL OR frequency_unit IN ('day','week','month','year','hour','cycle'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_trigger_condition_operator'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_trigger_condition_operator
            CHECK (trigger_condition_operator IS NULL OR trigger_condition_operator IN
                ('gt','gte','lt','lte','eq','neq'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_trigger_consistency'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_trigger_consistency
            CHECK (
                trigger_mechanism IS NULL
                OR (trigger_mechanism IN ('calendar','hours_based')
                    AND frequency_value IS NOT NULL AND frequency_unit IS NOT NULL
                    AND trigger_condition_parameter IS NULL AND trigger_condition_operator IS NULL
                    AND trigger_condition_value IS NULL AND trigger_condition_unit IS NULL
                    AND trigger_event_description IS NULL AND trigger_condition_context IS NULL)
                OR (trigger_mechanism = 'condition_based'
                    AND trigger_condition_parameter IS NOT NULL AND trigger_condition_operator IS NOT NULL
                    AND trigger_condition_value IS NOT NULL AND trigger_condition_unit IS NOT NULL
                    AND frequency_value IS NULL AND frequency_unit IS NULL
                    AND trigger_event_description IS NULL)
                OR (trigger_mechanism = 'event'
                    AND trigger_event_description IS NOT NULL
                    AND frequency_value IS NULL AND frequency_unit IS NULL
                    AND trigger_condition_parameter IS NULL AND trigger_condition_operator IS NULL
                    AND trigger_condition_value IS NULL AND trigger_condition_unit IS NULL
                    AND trigger_condition_context IS NULL)
                OR (trigger_mechanism = 'no_fixed_interval'
                    AND frequency_value IS NULL AND frequency_unit IS NULL
                    AND trigger_condition_parameter IS NULL AND trigger_condition_operator IS NULL
                    AND trigger_condition_value IS NULL AND trigger_condition_unit IS NULL
                    AND trigger_event_description IS NULL AND trigger_condition_context IS NULL)
            );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_trigger_context_only_condition'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_trigger_context_only_condition
            CHECK (trigger_condition_context IS NULL OR trigger_mechanism = 'condition_based');
    END IF;

    -- ---- task_templates: knowledge scope ----------------------------------
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_knowledge_scope'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_knowledge_scope
            CHECK (knowledge_scope IS NULL OR knowledge_scope IN ('shared','customer','marketplace'));
    END IF;

    -- marketplace is represented in the vocabulary but is NOT assignable until
    -- ownership/licensing/entitlement policy is separately ratified.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_marketplace_not_assignable'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_marketplace_not_assignable
            CHECK (knowledge_scope IS DISTINCT FROM 'marketplace');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_scope_organization'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_scope_organization
            CHECK (knowledge_scope IS NULL
                OR (knowledge_scope = 'shared'   AND organization_id IS NULL)
                OR (knowledge_scope = 'customer' AND organization_id IS NOT NULL));
    END IF;

    -- ---- task_templates: content origin -----------------------------------
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_content_origin'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_content_origin
            CHECK (content_origin IS NULL OR content_origin IN ('authored','legacy_generated'));
    END IF;

    -- An unclassified draft may exist, but nothing may be approved without an
    -- established origin; legacy-generated content additionally requires a
    -- recorded accountable clearance.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_origin_requires_authorship'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_origin_requires_authorship
            CHECK (review_state <> 'approved'
                OR content_origin = 'authored'
                OR (content_origin = 'legacy_generated'
                    AND legacy_clearance_by_user_id IS NOT NULL
                    AND legacy_clearance_at IS NOT NULL));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_legacy_clearance_consistent'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_legacy_clearance_consistent
            CHECK ((legacy_clearance_by_user_id IS NULL AND legacy_clearance_at IS NULL
                    AND legacy_clearance_rationale IS NULL)
                OR (legacy_clearance_by_user_id IS NOT NULL AND legacy_clearance_at IS NOT NULL));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_legacy_clearance_requires_legacy'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_legacy_clearance_requires_legacy
            CHECK (legacy_clearance_by_user_id IS NULL OR content_origin = 'legacy_generated');
    END IF;

    -- ---- task_templates: governed knowledge completeness ------------------
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_governed_knowledge_required'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_governed_knowledge_required
            CHECK (review_state <> 'approved'
                OR (knowledge_type_id IS NOT NULL
                    AND task_family_id IS NOT NULL
                    AND maintenance_strategy IS NOT NULL
                    AND trigger_mechanism IS NOT NULL
                    AND knowledge_scope IS NOT NULL));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_trigger_basis_required'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_trigger_basis_required
            CHECK (review_state <> 'approved'
                OR trigger_mechanism = 'no_fixed_interval'
                OR trigger_basis_source_version_id IS NOT NULL);
    END IF;

    -- Scheduling-shaped knowledge is prohibited for governed knowledge. The
    -- legacy columns are preserved for the reconciled corpus but may not carry
    -- values on an approved record. No scheduling capability is added.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_templates_no_scheduling_on_governed'
                   AND conrelid = 'task_templates'::regclass) THEN
        ALTER TABLE task_templates ADD CONSTRAINT chk_task_templates_no_scheduling_on_governed
            CHECK (review_state <> 'approved'
                OR (day_of_week IS NULL AND day_of_month IS NULL AND start_date IS NULL
                    AND frequency_type IS NULL AND frequency_interval IS NULL));
    END IF;

    -- ---- task_template_versions: mirrors ----------------------------------
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_maintenance_strategy'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_maintenance_strategy
            CHECK (maintenance_strategy IS NULL OR maintenance_strategy IN
                ('preventive','predictive','condition_based','compliance','corrective'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_trigger_mechanism'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_trigger_mechanism
            CHECK (trigger_mechanism IS NULL OR trigger_mechanism IN
                ('calendar','hours_based','condition_based','event','no_fixed_interval'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_frequency_unit_values'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_frequency_unit_values
            CHECK (frequency_unit IS NULL OR frequency_unit IN ('day','week','month','year','hour','cycle'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_trigger_condition_operator'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_trigger_condition_operator
            CHECK (trigger_condition_operator IS NULL OR trigger_condition_operator IN
                ('gt','gte','lt','lte','eq','neq'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_trigger_consistency'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_trigger_consistency
            CHECK (
                trigger_mechanism IS NULL
                OR (trigger_mechanism IN ('calendar','hours_based')
                    AND frequency_value IS NOT NULL AND frequency_unit IS NOT NULL
                    AND trigger_condition_parameter IS NULL AND trigger_condition_operator IS NULL
                    AND trigger_condition_value IS NULL AND trigger_condition_unit IS NULL
                    AND trigger_event_description IS NULL AND trigger_condition_context IS NULL)
                OR (trigger_mechanism = 'condition_based'
                    AND trigger_condition_parameter IS NOT NULL AND trigger_condition_operator IS NOT NULL
                    AND trigger_condition_value IS NOT NULL AND trigger_condition_unit IS NOT NULL
                    AND frequency_value IS NULL AND frequency_unit IS NULL
                    AND trigger_event_description IS NULL)
                OR (trigger_mechanism = 'event'
                    AND trigger_event_description IS NOT NULL
                    AND frequency_value IS NULL AND frequency_unit IS NULL
                    AND trigger_condition_parameter IS NULL AND trigger_condition_operator IS NULL
                    AND trigger_condition_value IS NULL AND trigger_condition_unit IS NULL
                    AND trigger_condition_context IS NULL)
                OR (trigger_mechanism = 'no_fixed_interval'
                    AND frequency_value IS NULL AND frequency_unit IS NULL
                    AND trigger_condition_parameter IS NULL AND trigger_condition_operator IS NULL
                    AND trigger_condition_value IS NULL AND trigger_condition_unit IS NULL
                    AND trigger_event_description IS NULL AND trigger_condition_context IS NULL)
            );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_trigger_context_only_condition'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_trigger_context_only_condition
            CHECK (trigger_condition_context IS NULL OR trigger_mechanism = 'condition_based');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_knowledge_scope'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_knowledge_scope
            CHECK (knowledge_scope IS NULL OR knowledge_scope IN ('shared','customer','marketplace'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_marketplace_not_assignable'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_marketplace_not_assignable
            CHECK (knowledge_scope IS DISTINCT FROM 'marketplace');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_scope_organization'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_scope_organization
            CHECK (knowledge_scope IS NULL
                OR (knowledge_scope = 'shared'   AND organization_id IS NULL)
                OR (knowledge_scope = 'customer' AND organization_id IS NOT NULL));
    END IF;

    -- lifecycle_state_at_publish is NOT NULL DEFAULT 'published', so every
    -- version row is a governed snapshot and must carry explicit governed fields.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_governed_knowledge_required'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_governed_knowledge_required
            CHECK (knowledge_type_id IS NOT NULL
                AND task_family_id IS NOT NULL
                AND maintenance_strategy IS NOT NULL
                AND trigger_mechanism IS NOT NULL
                AND knowledge_scope IS NOT NULL);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_template_versions_trigger_basis_required'
                   AND conrelid = 'task_template_versions'::regclass) THEN
        ALTER TABLE task_template_versions ADD CONSTRAINT chk_task_template_versions_trigger_basis_required
            CHECK (trigger_mechanism = 'no_fixed_interval'
                OR trigger_basis_source_version_id IS NOT NULL);
    END IF;

    -- ---- knowledge packs --------------------------------------------------
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_knowledge_packs_knowledge_scope'
                   AND conrelid = 'knowledge_packs'::regclass) THEN
        ALTER TABLE knowledge_packs ADD CONSTRAINT chk_knowledge_packs_knowledge_scope
            CHECK (knowledge_scope IS NULL OR knowledge_scope IN ('shared','customer','marketplace'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_knowledge_packs_marketplace_not_assignable'
                   AND conrelid = 'knowledge_packs'::regclass) THEN
        ALTER TABLE knowledge_packs ADD CONSTRAINT chk_knowledge_packs_marketplace_not_assignable
            CHECK (knowledge_scope IS DISTINCT FROM 'marketplace');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_knowledge_packs_scope_organization'
                   AND conrelid = 'knowledge_packs'::regclass) THEN
        ALTER TABLE knowledge_packs ADD CONSTRAINT chk_knowledge_packs_scope_organization
            CHECK (knowledge_scope IS NULL
                OR (knowledge_scope = 'shared'   AND organization_id IS NULL)
                OR (knowledge_scope = 'customer' AND organization_id IS NOT NULL));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_knowledge_pack_versions_knowledge_scope'
                   AND conrelid = 'knowledge_pack_versions'::regclass) THEN
        ALTER TABLE knowledge_pack_versions ADD CONSTRAINT chk_knowledge_pack_versions_knowledge_scope
            CHECK (knowledge_scope IS NULL OR knowledge_scope IN ('shared','customer','marketplace'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_knowledge_pack_versions_marketplace_not_assignable'
                   AND conrelid = 'knowledge_pack_versions'::regclass) THEN
        ALTER TABLE knowledge_pack_versions ADD CONSTRAINT chk_knowledge_pack_versions_marketplace_not_assignable
            CHECK (knowledge_scope IS DISTINCT FROM 'marketplace');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_knowledge_pack_versions_governed_scope_required'
                   AND conrelid = 'knowledge_pack_versions'::regclass) THEN
        ALTER TABLE knowledge_pack_versions ADD CONSTRAINT chk_knowledge_pack_versions_governed_scope_required
            CHECK (lifecycle_state NOT IN ('published','superseded','retired')
                OR knowledge_scope IS NOT NULL);
    END IF;
END
$$;

-- ===========================================================================
-- PART 8 — indexes
-- ===========================================================================

CREATE INDEX IF NOT EXISTS idx_task_templates_knowledge_type ON task_templates (knowledge_type_id);
CREATE INDEX IF NOT EXISTS idx_task_templates_task_family ON task_templates (task_family_id);
CREATE INDEX IF NOT EXISTS idx_task_templates_content_origin ON task_templates (content_origin);
CREATE INDEX IF NOT EXISTS idx_task_templates_knowledge_scope ON task_templates (knowledge_scope);
CREATE INDEX IF NOT EXISTS idx_task_template_versions_knowledge_type ON task_template_versions (knowledge_type_id);
CREATE INDEX IF NOT EXISTS idx_task_template_versions_task_family ON task_template_versions (task_family_id);
CREATE INDEX IF NOT EXISTS idx_ttet_equipment_type ON task_template_equipment_types (equipment_type_id);
CREATE INDEX IF NOT EXISTS idx_ttet_added_by_user ON task_template_equipment_types (added_by_user_id);
CREATE INDEX IF NOT EXISTS idx_ttvet_equipment_type ON task_template_version_equipment_types (equipment_type_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_packs_organization ON knowledge_packs (organization_id);

-- ===========================================================================
-- PART 9 — governance functions and triggers
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 9.1 content_origin is immutable once established.
-- ---------------------------------------------------------------------------
-- A NULL origin may be classified exactly once. Thereafter it can never change,
-- which is what (a) keeps legacy provenance permanently traceable and (b) makes
-- the classification backfill idempotent, because a transformed candidate always
-- retains legacy_generated and is therefore never re-matched by a NULL predicate.

CREATE OR REPLACE FUNCTION task_template_origin_immutability_check()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.content_origin IS NOT NULL
       AND NEW.content_origin IS DISTINCT FROM OLD.content_origin THEN
        RAISE EXCEPTION 'task_template % content_origin is immutable once established (was %, attempted %)',
            OLD.id, OLD.content_origin, NEW.content_origin
            USING ERRCODE = 'insufficient_privilege';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_task_templates_origin_immutable ON task_templates;

CREATE TRIGGER trg_task_templates_origin_immutable
    BEFORE UPDATE ON task_templates
    FOR EACH ROW
    EXECUTE FUNCTION task_template_origin_immutability_check();

-- ---------------------------------------------------------------------------
-- 9.2 Legacy clearance is a separate, accountable, write-once event.
-- ---------------------------------------------------------------------------
-- Clearance never mutates origin; it records that an accountable human accepted
-- responsibility for transforming legacy-generated material into governed
-- knowledge. The attribution FKs are RESTRICT so accountability cannot evaporate.

CREATE OR REPLACE FUNCTION task_template_legacy_clearance_guard()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.legacy_clearance_by_user_id IS NOT NULL
       AND OLD.legacy_clearance_by_user_id IS NULL THEN
        -- first clearance: the record must still be traceably legacy-generated
        IF NEW.content_origin IS DISTINCT FROM 'legacy_generated' THEN
            RAISE EXCEPTION 'task_template % clearance requires content_origin = legacy_generated', OLD.id
                USING ERRCODE = 'check_violation';
        END IF;
    ELSIF OLD.legacy_clearance_by_user_id IS NOT NULL
          AND NEW.legacy_clearance_by_user_id IS DISTINCT FROM OLD.legacy_clearance_by_user_id THEN
        -- clearance is write-once: accountable attribution is never reassigned
        RAISE EXCEPTION 'task_template % legacy clearance is write-once', OLD.id
            USING ERRCODE = 'insufficient_privilege';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_task_templates_legacy_clearance_guard ON task_templates;

CREATE TRIGGER trg_task_templates_legacy_clearance_guard
    BEFORE UPDATE ON task_templates
    FOR EACH ROW
    EXECUTE FUNCTION task_template_legacy_clearance_guard();

-- ---------------------------------------------------------------------------
-- 9.3 Publication admission for an immutable task-template version.
-- ---------------------------------------------------------------------------
-- Cross-row invariants that a CHECK cannot express. Deferred to COMMIT so that a
-- publisher may insert the version, its step versions, its frozen evidence and its
-- applicability inside one transaction and be judged on the final state — the
-- established 019 idiom. Enforced in the database so that a direct SQL write
-- cannot bypass admission.

CREATE OR REPLACE FUNCTION task_template_version_publication_admission()
RETURNS TRIGGER AS $$
DECLARE
    parent_origin TEXT;
    parent_cleared BOOLEAN;
    evidence_count INTEGER;
    applicability_count INTEGER;
    safety_control_count INTEGER;
BEGIN
    -- (a) origin: only authored knowledge, or legacy knowledge with recorded
    --     accountable clearance, may reach a governed version.
    SELECT t.content_origin,
           (t.legacy_clearance_by_user_id IS NOT NULL AND t.legacy_clearance_at IS NOT NULL)
      INTO parent_origin, parent_cleared
      FROM task_templates t
     WHERE t.id = NEW.task_template_id;

    IF parent_origin IS NULL THEN
        RAISE EXCEPTION 'task_template_version % cannot be governed: parent task_template % has no established content_origin',
            NEW.id, NEW.task_template_id USING ERRCODE = 'check_violation';
    END IF;

    IF parent_origin = 'legacy_generated' AND NOT COALESCE(parent_cleared, FALSE) THEN
        RAISE EXCEPTION 'task_template_version % cannot be governed: legacy_generated task_template % has no recorded accountable clearance',
            NEW.id, NEW.task_template_id USING ERRCODE = 'check_violation';
    END IF;

    -- (b) frozen evidence: the version itself or one of its step versions must
    --     carry provenance.
    SELECT count(*) INTO evidence_count
      FROM knowledge_template_version_evidence e
     WHERE e.task_template_version_id = NEW.id
        OR e.task_template_step_version_id IN (
               SELECT sv.id FROM task_template_step_versions sv
                WHERE sv.task_template_version_id = NEW.id);

    IF evidence_count = 0 THEN
        RAISE EXCEPTION 'task_template_version % cannot be governed: no frozen evidence row exists',
            NEW.id USING ERRCODE = 'check_violation';
    END IF;

    -- (c) safety review: when the version carries safety controls the reviewer must
    --     have attested that controls are defined. This is a single attestation over
    --     the control set; it does NOT assert per-control provenance, which is
    --     deliberately unsupported.
    SELECT count(*) INTO safety_control_count
      FROM task_template_safety_control_versions scv
     WHERE scv.task_template_version_id = NEW.id;

    IF safety_control_count > 0 AND NEW.safety_review_state IS DISTINCT FROM 'reviewed_controls_defined' THEN
        RAISE EXCEPTION 'task_template_version % carries % safety control(s) but safety_review_state is %; reviewer attestation over defined controls is required',
            NEW.id, safety_control_count, COALESCE(NEW.safety_review_state, 'NULL')
            USING ERRCODE = 'check_violation';
    END IF;

    -- (d) applicability: a governed version must declare at least one Equipment Type.
    SELECT count(*) INTO applicability_count
      FROM task_template_version_equipment_types x
     WHERE x.task_template_version_id = NEW.id;

    IF applicability_count = 0 THEN
        RAISE EXCEPTION 'task_template_version % cannot be governed: no Equipment Type applicability is recorded',
            NEW.id USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_task_template_version_publication_admission ON task_template_versions;

CREATE CONSTRAINT TRIGGER trg_task_template_version_publication_admission
    AFTER INSERT OR UPDATE ON task_template_versions
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION task_template_version_publication_admission();

-- ---------------------------------------------------------------------------
-- 9.4 Knowledge Pack ownership scope.
-- ---------------------------------------------------------------------------
-- A governed pack version must record an explicit scope, and the pack identity
-- must have established its ownership before any governed version exists.
--
-- R1 REMEDIATION: a Pack version's scope is a SNAPSHOT of the ownership its Pack
-- already declared, so the two can never legitimately disagree — at any lifecycle
-- state, not only at publication. The consistency check below therefore runs
-- unconditionally (before the governed-state early return), because an
-- inconsistent draft snapshot could otherwise be carried into a governed state,
-- and because a version must never assert an ownership its Pack does not have.

CREATE OR REPLACE FUNCTION knowledge_pack_version_scope_governed_check()
RETURNS TRIGGER AS $$
DECLARE
    pack_scope TEXT;
BEGIN
    SELECT p.knowledge_scope INTO pack_scope
      FROM knowledge_packs p WHERE p.id = NEW.knowledge_pack_id;

    -- The snapshot must equal the Pack's established ownership. Written as a
    -- null-safe comparison so that an unscoped Pack accepts only an unscoped
    -- draft, and a scoped Pack never accepts an unscoped or different snapshot.
    IF NEW.knowledge_scope IS DISTINCT FROM pack_scope THEN
        RAISE EXCEPTION 'knowledge_pack_version % declares knowledge scope % but its pack % has established %',
            NEW.id, COALESCE(NEW.knowledge_scope, 'NULL'), NEW.knowledge_pack_id,
            COALESCE(pack_scope, 'no scope')
            USING ERRCODE = 'check_violation';
    END IF;

    IF NEW.lifecycle_state NOT IN ('published','superseded','retired') THEN
        RETURN NULL;
    END IF;

    IF NEW.knowledge_scope IS NULL THEN
        RAISE EXCEPTION 'knowledge_pack_version % cannot be governed: no explicit knowledge scope',
            NEW.id USING ERRCODE = 'check_violation';
    END IF;

    IF pack_scope IS NULL THEN
        RAISE EXCEPTION 'knowledge_pack_version % cannot be governed: pack % has no established ownership scope',
            NEW.id, NEW.knowledge_pack_id USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_knowledge_pack_version_scope_governed ON knowledge_pack_versions;

CREATE CONSTRAINT TRIGGER trg_knowledge_pack_version_scope_governed
    AFTER INSERT OR UPDATE ON knowledge_pack_versions
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION knowledge_pack_version_scope_governed_check();

-- ---------------------------------------------------------------------------
-- 9.5 Pack membership scope compatibility.
-- ---------------------------------------------------------------------------
-- Shared packs may contain only shared knowledge. Customer packs may contain
-- shared knowledge plus customer knowledge of the same organization. Marketplace
-- packs cannot exist under the assignability guard.
--
-- R1 REMEDIATION: the rule above was too permissive and disagreed with the
-- application service. ATM-001 M6.3 ratifies a single member rule — a Pack member
-- must be globally applicable (shared) knowledge. A customer-owned Pack may
-- exist (it is a tenant's curated pack identity), but customer ownership of the
-- Pack does NOT authorize customer-scoped member knowledge during M6.3:
--
--   shared Pack   -> shared member    permitted
--   customer Pack -> shared member    permitted
--   customer Pack -> customer member  REFUSED
--   marketplace                       not assignable, hence unreachable
--
-- Storage now enforces the same rule the service enforces, so a direct SQL write
-- can no longer compose a pack the service would refuse. The tighter rule is
-- adopted by storage; the service is not weakened.

CREATE OR REPLACE FUNCTION knowledge_pack_membership_scope_compatibility()
RETURNS TRIGGER AS $$
DECLARE
    pack_scope TEXT;
    member_scope TEXT;
BEGIN
    SELECT v.knowledge_scope
      INTO pack_scope
      FROM knowledge_pack_versions v
     WHERE v.id = NEW.knowledge_pack_version_id;

    SELECT tv.knowledge_scope
      INTO member_scope
      FROM task_template_versions tv
     WHERE tv.id = NEW.task_template_version_id;

    IF pack_scope IS NULL OR member_scope IS NULL THEN
        RAISE EXCEPTION 'pack membership requires explicit knowledge scope on both the pack version and the member version'
            USING ERRCODE = 'check_violation';
    END IF;

    IF member_scope <> 'shared' THEN
        RAISE EXCEPTION 'pack version % may not contain % knowledge: an M6.3 pack member must be globally applicable (shared) knowledge',
            NEW.knowledge_pack_version_id, member_scope USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_kpvtv_scope_compatibility_insert ON knowledge_pack_version_task_template_versions;
DROP TRIGGER IF EXISTS trg_kpvtv_scope_compatibility_update ON knowledge_pack_version_task_template_versions;

CREATE CONSTRAINT TRIGGER trg_kpvtv_scope_compatibility_insert
    AFTER INSERT ON knowledge_pack_version_task_template_versions
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION knowledge_pack_membership_scope_compatibility();

CREATE CONSTRAINT TRIGGER trg_kpvtv_scope_compatibility_update
    AFTER UPDATE ON knowledge_pack_version_task_template_versions
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION knowledge_pack_membership_scope_compatibility();

-- ===========================================================================
-- PART 9b — R1 remediation: durable storage guards
-- ===========================================================================
-- Three defects allowed direct SQL to mutate governed state that must be
-- durable. Each guard below mirrors a mechanism the architecture already
-- expresses elsewhere (migration 011's frozen-evidence immutability, migration
-- 009's sealed step-set, migration 020's own content_origin immutability), so no
-- new governance concept is introduced.

-- ---------------------------------------------------------------------------
-- 9b.1 Frozen Equipment-Type applicability is immutable once the version is sealed.
-- ---------------------------------------------------------------------------
-- Migration 009 seals a version's step set; migration 011 refuses to attach
-- provenance to an already-sealed version. The frozen applicability set is the
-- third component of the same frozen boundary — it is what a published procedure
-- applies to — so it is closed by the same seal:
--
--   * INSERT is refused once the parent version is sealed (construction is
--     unaffected: the publication path writes applicability before sealing);
--   * UPDATE and DELETE are refused unconditionally, because a frozen
--     applicability row may never be retargeted or removed.
--
-- Applicability rows are immutable precisely as frozen evidence rows are, and for
-- the same reason: the frozen set is a governance claim, not a mutable join.

CREATE OR REPLACE FUNCTION task_template_version_applicability_insert_guard()
RETURNS TRIGGER AS $$
DECLARE
    sealed BOOLEAN;
BEGIN
    SELECT v.is_step_set_sealed INTO sealed
      FROM task_template_versions v
     WHERE v.id = NEW.task_template_version_id;

    IF sealed IS TRUE THEN
        RAISE EXCEPTION 'cannot add Equipment-Type applicability to sealed task_template_version %',
            NEW.task_template_version_id USING ERRCODE = 'insufficient_privilege';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION task_template_version_applicability_immutable_check()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'task_template_version_equipment_types is immutable and cannot be %', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ttvet_insert_before_seal ON task_template_version_equipment_types;
DROP TRIGGER IF EXISTS trg_ttvet_immutable ON task_template_version_equipment_types;

CREATE TRIGGER trg_ttvet_insert_before_seal
    BEFORE INSERT ON task_template_version_equipment_types
    FOR EACH ROW
    EXECUTE FUNCTION task_template_version_applicability_insert_guard();

CREATE TRIGGER trg_ttvet_immutable
    BEFORE UPDATE OR DELETE ON task_template_version_equipment_types
    FOR EACH ROW
    EXECUTE FUNCTION task_template_version_applicability_immutable_check();

-- ---------------------------------------------------------------------------
-- 9b.2 Pack ownership is durable once a Pack version exists.
-- ---------------------------------------------------------------------------
-- A Pack version snapshots the ownership its Pack declared, and a published
-- version is immutable. If the Pack identity's ownership could still be rewritten,
-- the frozen snapshot would silently describe an ownership the Pack no longer
-- has — the version would keep asserting one thing while its parent said another.
-- Ownership may therefore be corrected only while the Pack has no versions at all,
-- which is the window in which nothing yet depends on it.
--
-- This does not introduce a general licensing mechanism: it fixes exactly one
-- column pair, on exactly one table, for exactly as long as a version depends on it.

CREATE OR REPLACE FUNCTION knowledge_pack_ownership_durability_check()
RETURNS TRIGGER AS $$
DECLARE
    version_count INTEGER;
BEGIN
    IF NEW.knowledge_scope IS NOT DISTINCT FROM OLD.knowledge_scope
       AND NEW.organization_id IS NOT DISTINCT FROM OLD.organization_id THEN
        RETURN NEW;
    END IF;

    SELECT count(*) INTO version_count
      FROM knowledge_pack_versions v
     WHERE v.knowledge_pack_id = OLD.id;

    IF version_count > 0 THEN
        RAISE EXCEPTION 'knowledge_pack % ownership is durable: % version(s) already snapshot it (was scope %, attempted %)',
            OLD.id, version_count, COALESCE(OLD.knowledge_scope, 'NULL'),
            COALESCE(NEW.knowledge_scope, 'NULL')
            USING ERRCODE = 'insufficient_privilege';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_knowledge_packs_ownership_durable ON knowledge_packs;

CREATE TRIGGER trg_knowledge_packs_ownership_durable
    BEFORE UPDATE ON knowledge_packs
    FOR EACH ROW
    EXECUTE FUNCTION knowledge_pack_ownership_durability_check();

-- ===========================================================================
-- PART 10 — legacy corpus classification and applicability backfill
-- ===========================================================================
-- A single self-contained statement so the migration behaves identically whether
-- it is applied as one batch (the runner sends the whole file as one simple-query
-- message) or statement by statement (psql -f, autocommit). No temporary object
-- and no cross-statement state is used.
--
-- The legacy identity set is an explicit frozen manifest, not a timestamp and not
-- a heuristic predicate. Three outcomes are permitted and no others:
--   * zero manifest identities present  -> corpus absent  -> allowed no-op
--   * all 846 manifest identities present -> classify exactly those unclassified rows
--   * anything else                     -> RAISE; the transaction rolls back and
--                                          nothing is partially classified,
--                                          silently repaired or inferred.
--
-- No timestamp, created_by, organization_id, seed_batch_id, is_system or name
-- pattern participates in the predicate.

DO $$
DECLARE
    -- Frozen from docs/research/m6r1/maintenance-procedure-reconciliation.jsonl
    -- (846 records, sha256 prefix 8e0e32e522b6c519). Id 1100..1945.
    v_manifest TEXT :=
        '1100:AC_MOTOR_INSPECTION,'
        '1101:AC_MOTOR_SAFETY_CHECK,'
        '1102:AC_MOTOR_TESTING,'
        '1103:DC_MOTOR_INSPECTION,'
        '1104:DC_MOTOR_SAFETY_CHECK,'
        '1105:DC_MOTOR_TESTING,'
        '1106:SYNC_MOTOR_INSPECTION,'
        '1107:SYNC_MOTOR_SAFETY_CHECK,'
        '1108:SYNC_MOTOR_TESTING,'
        '1109:SUBM_MOTOR_INSPECTION,'
        '1110:SUBM_MOTOR_SAFETY_CHECK,'
        '1111:SUBM_MOTOR_TESTING,'
        '1112:DIESEL_GEN_INSPECTION,'
        '1113:DIESEL_GEN_SAFETY_CHECK,'
        '1114:DIESEL_GEN_TESTING,'
        '1115:EMERG_GEN_INSPECTION,'
        '1116:EMERG_GEN_SAFETY_CHECK,'
        '1117:EMERG_GEN_TESTING,'
        '1118:PWR_XFMR_INSPECTION,'
        '1119:PWR_XFMR_SAFETY_CHECK,'
        '1120:PWR_XFMR_TESTING,'
        '1121:DIST_XFMR_INSPECTION,'
        '1122:DIST_XFMR_SAFETY_CHECK,'
        '1123:DIST_XFMR_TESTING,'
        '1124:DRY_XFMR_INSPECTION,'
        '1125:DRY_XFMR_SAFETY_CHECK,'
        '1126:DRY_XFMR_TESTING,'
        '1127:OIL_XFMR_INSPECTION,'
        '1128:OIL_XFMR_SAFETY_CHECK,'
        '1129:OIL_XFMR_TESTING,'
        '1130:LV_SWGR_INSPECTION,'
        '1131:LV_SWGR_SAFETY_CHECK,'
        '1132:LV_SWGR_TESTING,'
        '1133:MV_SWGR_INSPECTION,'
        '1134:MV_SWGR_SAFETY_CHECK,'
        '1135:MV_SWGR_TESTING,'
        '1136:MCC_INSPECTION,'
        '1137:MCC_SAFETY_CHECK,'
        '1138:MCC_TESTING,'
        '1139:ACB_INSPECTION,'
        '1140:ACB_SAFETY_CHECK,'
        '1141:ACB_TESTING,'
        '1142:VCB_INSPECTION,'
        '1143:VCB_SAFETY_CHECK,'
        '1144:VCB_TESTING,'
        '1145:DIST_PANEL_INSPECTION,'
        '1146:DIST_PANEL_SAFETY_CHECK,'
        '1147:DIST_PANEL_TESTING,'
        '1148:CTRL_PANEL_INSPECTION,'
        '1149:CTRL_PANEL_SAFETY_CHECK,'
        '1150:CTRL_PANEL_TESTING,'
        '1151:UPS_INSPECTION,'
        '1152:UPS_SAFETY_CHECK,'
        '1153:UPS_TESTING,'
        '1154:BATT_BANK_INSPECTION,'
        '1155:BATT_BANK_SAFETY_CHECK,'
        '1156:BATT_BANK_TESTING,'
        '1157:VFD_INSPECTION,'
        '1158:VFD_SAFETY_CHECK,'
        '1159:VFD_TESTING,'
        '1160:SOFT_START_INSPECTION,'
        '1161:SOFT_START_SAFETY_CHECK,'
        '1162:SOFT_START_TESTING,'
        '1163:RECTIFIER_INSPECTION,'
        '1164:RECTIFIER_SAFETY_CHECK,'
        '1165:RECTIFIER_TESTING,'
        '1166:INVERTER_INSPECTION,'
        '1167:INVERTER_SAFETY_CHECK,'
        '1168:INVERTER_TESTING,'
        '1169:CAP_BANK_INSPECTION,'
        '1170:CAP_BANK_SAFETY_CHECK,'
        '1171:CAP_BANK_TESTING,'
        '1172:SPLIT_CASE_INSPECTION,'
        '1173:SPLIT_CASE_SAFETY_CHECK,'
        '1174:SPLIT_CASE_TESTING,'
        '1175:VERT_TURB_INSPECTION,'
        '1176:VERT_TURB_SAFETY_CHECK,'
        '1177:VERT_TURB_TESTING,'
        '1178:CIRCULAT_INSPECTION,'
        '1179:CIRCULAT_SAFETY_CHECK,'
        '1180:CIRCULAT_TESTING,'
        '1181:SEWAGE_INSPECTION,'
        '1182:SEWAGE_SAFETY_CHECK,'
        '1183:SEWAGE_TESTING,'
        '1184:DRAINAGE_INSPECTION,'
        '1185:DRAINAGE_SAFETY_CHECK,'
        '1186:DRAINAGE_TESTING,'
        '1187:SLURRY_INSPECTION,'
        '1188:SLURRY_SAFETY_CHECK,'
        '1189:SLURRY_TESTING,'
        '1190:PLUNGER_INSPECTION,'
        '1191:PLUNGER_SAFETY_CHECK,'
        '1192:PLUNGER_TESTING,'
        '1193:PISTON_INSPECTION,'
        '1194:PISTON_SAFETY_CHECK,'
        '1195:PISTON_TESTING,'
        '1196:DIAPH_HY_INSPECTION,'
        '1197:DIAPH_HY_SAFETY_CHECK,'
        '1198:DIAPH_HY_TESTING,'
        '1199:ODP_INSPECTION,'
        '1200:ODP_SAFETY_CHECK,'
        '1201:ODP_TESTING,'
        '1202:WP_INSPECTION,'
        '1203:WP_SAFETY_CHECK,'
        '1204:WP_TESTING,'
        '1205:BRAKE_INSPECTION,'
        '1206:BRAKE_SAFETY_CHECK,'
        '1207:BRAKE_TESTING,'
        '1208:VAR_SPD_INSPECTION,'
        '1209:VAR_SPD_SAFETY_CHECK,'
        '1210:VAR_SPD_TESTING,'
        '1211:RISING_ST_INSPECTION,'
        '1212:RISING_ST_SAFETY_CHECK,'
        '1213:RISING_ST_TESTING,'
        '1214:NON_RISE_INSPECTION,'
        '1215:NON_RISE_SAFETY_CHECK,'
        '1216:NON_RISE_TESTING,'
        '1217:KNIFE_INSPECTION,'
        '1218:KNIFE_SAFETY_CHECK,'
        '1219:KNIFE_TESTING,'
        '1220:CONC_INSPECTION,'
        '1221:CONC_SAFETY_CHECK,'
        '1222:CONC_TESTING,'
        '1223:DOUB_OFF_INSPECTION,'
        '1224:DOUB_OFF_SAFETY_CHECK,'
        '1225:DOUB_OFF_TESTING,'
        '1226:TRIP_OFF_INSPECTION,'
        '1227:TRIP_OFF_SAFETY_CHECK,'
        '1228:TRIP_OFF_TESTING,'
        '1229:SWING_INSPECTION,'
        '1230:SWING_SAFETY_CHECK,'
        '1231:SWING_TESTING,'
        '1232:LIFT_INSPECTION,'
        '1233:LIFT_SAFETY_CHECK,'
        '1234:LIFT_TESTING,'
        '1235:DUAL_PL_INSPECTION,'
        '1236:DUAL_PL_SAFETY_CHECK,'
        '1237:DUAL_PL_TESTING,'
        '1238:NOZZLE_INSPECTION,'
        '1239:NOZZLE_SAFETY_CHECK,'
        '1240:NOZZLE_TESTING,'
        '1241:GAUGE_INSPECTION,'
        '1242:GAUGE_SAFETY_CHECK,'
        '1243:GAUGE_TESTING,'
        '1244:ABS_INSPECTION,'
        '1245:ABS_SAFETY_CHECK,'
        '1246:ABS_TESTING,'
        '1247:DIFF_INSPECTION,'
        '1248:DIFF_SAFETY_CHECK,'
        '1249:DIFF_TESTING,'
        '1250:HYDRO_INSPECTION,'
        '1251:HYDRO_SAFETY_CHECK,'
        '1252:HYDRO_TESTING,'
        '1253:ELEC_MAG_INSPECTION,'
        '1254:ELEC_MAG_SAFETY_CHECK,'
        '1255:ELEC_MAG_TESTING,'
        '1256:ULTRA_INSPECTION,'
        '1257:ULTRA_SAFETY_CHECK,'
        '1258:ULTRA_TESTING,'
        '1259:VORTEX_INSPECTION,'
        '1260:VORTEX_SAFETY_CHECK,'
        '1261:VORTEX_TESTING,'
        '1262:TURBINE_INSPECTION,'
        '1263:TURBINE_SAFETY_CHECK,'
        '1264:TURBINE_TESTING,'
        '1265:ORIFICE_INSPECTION,'
        '1266:ORIFICE_SAFETY_CHECK,'
        '1267:ORIFICE_TESTING,'
        '1268:VENTURI_INSPECTION,'
        '1269:VENTURI_SAFETY_CHECK,'
        '1270:VENTURI_TESTING,'
        '1271:RADAR_INSPECTION,'
        '1272:RADAR_SAFETY_CHECK,'
        '1273:RADAR_TESTING,'
        '1274:ULTRA_LVL_INSPECTION,'
        '1275:ULTRA_LVL_SAFETY_CHECK,'
        '1276:ULTRA_LVL_TESTING,'
        '1277:CAPAC_INSPECTION,'
        '1278:CAPAC_SAFETY_CHECK,'
        '1279:CAPAC_TESTING,'
        '1280:FLOAT_INSPECTION,'
        '1281:FLOAT_SAFETY_CHECK,'
        '1282:FLOAT_TESTING,'
        '1283:RTD_INSPECTION,'
        '1284:RTD_SAFETY_CHECK,'
        '1285:RTD_TESTING,'
        '1286:THERMO_INSPECTION,'
        '1287:THERMO_SAFETY_CHECK,'
        '1288:THERMO_TESTING,'
        '1289:INFRA_INSPECTION,'
        '1290:INFRA_SAFETY_CHECK,'
        '1291:INFRA_TESTING,'
        '1292:MODULAR_INSPECTION,'
        '1293:MODULAR_SAFETY_CHECK,'
        '1294:MODULAR_TESTING,'
        '1295:COMPACT_INSPECTION,'
        '1296:COMPACT_SAFETY_CHECK,'
        '1297:COMPACT_TESTING,'
        '1298:SAFETY_INSPECTION,'
        '1299:SAFETY_SAFETY_CHECK,'
        '1300:SAFETY_TESTING,'
        '1301:MULTI_INSPECTION,'
        '1302:MULTI_SAFETY_CHECK,'
        '1303:MULTI_TESTING,'
        '1304:TWIN_LOBE_INSPECTION,'
        '1305:TWIN_LOBE_SAFETY_CHECK,'
        '1306:TWIN_LOBE_TESTING,'
        '1307:TRI_LOBE_INSPECTION,'
        '1308:TRI_LOBE_SAFETY_CHECK,'
        '1309:TRI_LOBE_TESTING,'
        '1310:OIL_INJ_INSPECTION,'
        '1311:OIL_INJ_SAFETY_CHECK,'
        '1312:OIL_INJ_TESTING,'
        '1313:OIL_FREE_INSPECTION,'
        '1314:OIL_FREE_SAFETY_CHECK,'
        '1315:OIL_FREE_TESTING,'
        '1316:RAPID_INSPECTION,'
        '1317:RAPID_SAFETY_CHECK,'
        '1318:RAPID_TESTING,'
        '1319:PRESSURE_INSPECTION,'
        '1320:PRESSURE_SAFETY_CHECK,'
        '1321:PRESSURE_TESTING,'
        '1322:CONT_INSPECTION,'
        '1323:CONT_SAFETY_CHECK,'
        '1324:CONT_TESTING,'
        '1325:MF_INSPECTION,'
        '1326:MF_SAFETY_CHECK,'
        '1327:MF_TESTING,'
        '1328:UF_INSPECTION,'
        '1329:UF_SAFETY_CHECK,'
        '1330:UF_TESTING,'
        '1331:RO_INSPECTION,'
        '1332:RO_SAFETY_CHECK,'
        '1333:RO_TESTING,'
        '1334:TURBO_INSPECTION,'
        '1335:TURBO_SAFETY_CHECK,'
        '1336:TURBO_TESTING,'
        '1337:PROPELL_INSPECTION,'
        '1338:PROPELL_SAFETY_CHECK,'
        '1339:PROPELL_TESTING,'
        '1340:PADDLE_INSPECTION,'
        '1341:PADDLE_SAFETY_CHECK,'
        '1342:PADDLE_TESTING,'
        '1343:FINE_BUB_INSPECTION,'
        '1344:FINE_BUB_SAFETY_CHECK,'
        '1345:FINE_BUB_TESTING,'
        '1346:COARSE_INSPECTION,'
        '1347:COARSE_SAFETY_CHECK,'
        '1348:COARSE_TESTING,'
        '1349:MANUAL_INSPECTION,'
        '1350:MANUAL_SAFETY_CHECK,'
        '1351:MANUAL_TESTING,'
        '1352:MECH_INSPECTION,'
        '1353:MECH_SAFETY_CHECK,'
        '1354:MECH_TESTING,'
        '1355:FINE_STEP_INSPECTION,'
        '1356:FINE_STEP_SAFETY_CHECK,'
        '1357:FINE_STEP_TESTING,'
        '1358:PERF_INSPECTION,'
        '1359:PERF_SAFETY_CHECK,'
        '1360:PERF_TESTING,'
        '1361:SHAFTED_INSPECTION,'
        '1362:SHAFTED_SAFETY_CHECK,'
        '1363:SHAFTED_TESTING,'
        '1364:SHAFTLESS_INSPECTION,'
        '1365:SHAFTLESS_SAFETY_CHECK,'
        '1366:SHAFTLESS_TESTING,'
        '1367:COMPACT_INSPECTION,'
        '1368:COMPACT_SAFETY_CHECK,'
        '1369:COMPACT_TESTING,'
        '1370:AERO_TURB_INSPECTION,'
        '1371:AERO_TURB_SAFETY_CHECK,'
        '1372:AERO_TURB_TESTING,'
        '1373:AGIT_VESSEL_INSPECTION,'
        '1374:AGIT_VESSEL_SAFETY_CHECK,'
        '1375:AGIT_VESSEL_TESTING,'
        '1376:AIR_COOLER_INSPECTION,'
        '1377:AIR_COOLER_SAFETY_CHECK,'
        '1378:AIR_COOLER_TESTING,'
        '1379:AHU_INSPECTION,'
        '1380:AHU_SAFETY_CHECK,'
        '1381:AHU_TESTING,'
        '1382:ACC_INSPECTION,'
        '1383:ACC_SAFETY_CHECK,'
        '1384:ACC_TESTING,'
        '1385:AIS_SWGR_INSPECTION,'
        '1386:AIS_SWGR_SAFETY_CHECK,'
        '1387:AIS_SWGR_TESTING,'
        '1388:API_TANK_INSPECTION,'
        '1389:API_TANK_SAFETY_CHECK,'
        '1390:API_TANK_TESTING,'
        '1391:APRON_FEED_INSPECTION,'
        '1392:APRON_FEED_SAFETY_CHECK,'
        '1393:APRON_FEED_TESTING,'
        '1394:ART_DUMP_INSPECTION,'
        '1395:ART_DUMP_SAFETY_CHECK,'
        '1396:ART_DUMP_TESTING,'
        '1397:ART_ROBOT_INSPECTION,'
        '1398:ART_ROBOT_SAFETY_CHECK,'
        '1399:ART_ROBOT_TESTING,'
        '1400:AGV_INSPECTION,'
        '1401:AGV_SAFETY_CHECK,'
        '1402:AGV_TESTING,'
        '1403:BAGHOUSE_INSPECTION,'
        '1404:BAGHOUSE_SAFETY_CHECK,'
        '1405:BAGHOUSE_TESTING,'
        '1406:BALL_MILL_INSPECTION,'
        '1407:BALL_MILL_SAFETY_CHECK,'
        '1408:BALL_MILL_TESTING,'
        '1409:BASKET_CENT_INSPECTION,'
        '1410:BASKET_CENT_SAFETY_CHECK,'
        '1411:BASKET_CENT_TESTING,'
        '1412:BATCH_REACT_INSPECTION,'
        '1413:BATCH_REACT_SAFETY_CHECK,'
        '1414:BATCH_REACT_TESTING,'
        '1415:BELT_FILT_INSPECTION,'
        '1416:BELT_FILT_SAFETY_CHECK,'
        '1417:BELT_FILT_TESTING,'
        '1418:BLANK_PRESS_INSPECTION,'
        '1419:BLANK_PRESS_SAFETY_CHECK,'
        '1420:BLANK_PRESS_TESTING,'
        '1421:BLOW_MACH_INSPECTION,'
        '1422:BLOW_MACH_SAFETY_CHECK,'
        '1423:BLOW_MACH_TESTING,'
        '1424:BOP_INSPECTION,'
        '1425:BOP_SAFETY_CHECK,'
        '1426:BOP_TESTING,'
        '1427:BFP_INSPECTION,'
        '1428:BFP_SAFETY_CHECK,'
        '1429:BFP_TESTING,'
        '1430:BOT_ASH_CONV_INSPECTION,'
        '1431:BOT_ASH_CONV_SAFETY_CHECK,'
        '1432:BOT_ASH_CONV_TESTING,'
        '1433:BUCK_ELEV_INSPECTION,'
        '1434:BUCK_ELEV_SAFETY_CHECK,'
        '1435:BUCK_ELEV_TESTING,'
        '1436:BULLDOZER_INSPECTION,'
        '1437:BULLDOZER_SAFETY_CHECK,'
        '1438:BULLDOZER_TESTING,'
        '1439:BULLET_TANK_INSPECTION,'
        '1440:BULLET_TANK_SAFETY_CHECK,'
        '1441:BULLET_TANK_TESTING,'
        '1442:CART_ROBOT_INSPECTION,'
        '1443:CART_ROBOT_SAFETY_CHECK,'
        '1444:CART_ROBOT_TESTING,'
        '1445:CART_COLL_INSPECTION,'
        '1446:CART_COLL_SAFETY_CHECK,'
        '1447:CART_COLL_TESTING,'
        '1448:CASE_PACK_INSPECTION,'
        '1449:CASE_PACK_SAFETY_CHECK,'
        '1450:CASE_PACK_TESTING,'
        '1451:CENT_AIR_COMP_INSPECTION,'
        '1452:CENT_AIR_COMP_SAFETY_CHECK,'
        '1453:CENT_AIR_COMP_TESTING,'
        '1454:CHAIN_CONV_INSPECTION,'
        '1455:CHAIN_CONV_SAFETY_CHECK,'
        '1456:CHAIN_CONV_TESTING,'
        '1457:CHEM_TRANS_PUMP_INSPECTION,'
        '1458:CHEM_TRANS_PUMP_SAFETY_CHECK,'
        '1459:CHEM_TRANS_PUMP_TESTING,'
        '1460:CHILLER_INSPECTION,'
        '1461:CHILLER_SAFETY_CHECK,'
        '1462:CHILLER_TESTING,'
        '1463:CHIMNEY_INSPECTION,'
        '1464:CHIMNEY_SAFETY_CHECK,'
        '1465:CHIMNEY_TESTING,'
        '1466:XMAS_TREE_INSPECTION,'
        '1467:XMAS_TREE_SAFETY_CHECK,'
        '1468:XMAS_TREE_TESTING,'
        '1469:CW_PUMP_INSPECTION,'
        '1470:CW_PUMP_SAFETY_CHECK,'
        '1471:CW_PUMP_TESTING,'
        '1472:CNC_LATHE_INSPECTION,'
        '1473:CNC_LATHE_SAFETY_CHECK,'
        '1474:CNC_LATHE_TESTING,'
        '1475:CNC_MILL_INSPECTION,'
        '1476:CNC_MILL_SAFETY_CHECK,'
        '1477:CNC_MILL_TESTING,'
        '1478:COAL_PULV_INSPECTION,'
        '1479:COAL_PULV_SAFETY_CHECK,'
        '1480:COAL_PULV_TESTING,'
        '1481:COALESCER_INSPECTION,'
        '1482:COALESCER_SAFETY_CHECK,'
        '1483:COALESCER_TESTING,'
        '1484:COBOT_INSPECTION,'
        '1485:COBOT_SAFETY_CHECK,'
        '1486:COBOT_TESTING,'
        '1487:COND_PUMP_INSPECTION,'
        '1488:COND_PUMP_SAFETY_CHECK,'
        '1489:COND_PUMP_TESTING,'
        '1490:CONDENSER_INSPECTION,'
        '1491:CONDENSER_SAFETY_CHECK,'
        '1492:CONDENSER_TESTING,'
        '1493:CONE_CRUSH_INSPECTION,'
        '1494:CONE_CRUSH_SAFETY_CHECK,'
        '1495:CONE_CRUSH_TESTING,'
        '1496:CONT_MINER_INSPECTION,'
        '1497:CONT_MINER_SAFETY_CHECK,'
        '1498:CONT_MINER_TESTING,'
        '1499:CORIOLIS_INSPECTION,'
        '1500:CORIOLIS_SAFETY_CHECK,'
        '1501:CORIOLIS_TESTING,'
        '1502:CRYSTAL_INSPECTION,'
        '1503:CRYSTAL_SAFETY_CHECK,'
        '1504:CRYSTAL_TESTING,'
        '1505:CSTR_INSPECTION,'
        '1506:CSTR_SAFETY_CHECK,'
        '1507:CSTR_TESTING,'
        '1508:CYCLONE_INSPECTION,'
        '1509:CYCLONE_SAFETY_CHECK,'
        '1510:CYCLONE_TESTING,'
        '1511:DAY_BIN_INSPECTION,'
        '1512:DAY_BIN_SAFETY_CHECK,'
        '1513:DAY_BIN_TESTING,'
        '1514:DEAERATOR_INSPECTION,'
        '1515:DEAERATOR_SAFETY_CHECK,'
        '1516:DEAERATOR_TESTING,'
        '1517:DECANT_CENT_INSPECTION,'
        '1518:DECANT_CENT_SAFETY_CHECK,'
        '1519:DECANT_CENT_TESTING,'
        '1520:DESANDER_INSPECTION,'
        '1521:DESANDER_SAFETY_CHECK,'
        '1522:DESANDER_TESTING,'
        '1523:DESILTER_INSPECTION,'
        '1524:DESILTER_SAFETY_CHECK,'
        '1525:DESILTER_TESTING,'
        '1526:DIAPH_COMP_INSPECTION,'
        '1527:DIAPH_COMP_SAFETY_CHECK,'
        '1528:DIAPH_COMP_TESTING,'
        '1529:DISC_CENT_INSPECTION,'
        '1530:DISC_CENT_SAFETY_CHECK,'
        '1531:DISC_CENT_TESTING,'
        '1532:DIST_COL_INSPECTION,'
        '1533:DIST_COL_SAFETY_CHECK,'
        '1534:DIST_COL_TESTING,'
        '1535:DP_EX_INSPECTION,'
        '1536:DP_EX_SAFETY_CHECK,'
        '1537:DP_EX_TESTING,'
        '1538:DRAWWORKS_INSPECTION,'
        '1539:DRAWWORKS_SAFETY_CHECK,'
        '1540:DRAWWORKS_TESTING,'
        '1541:DRUM_BOIL_INSPECTION,'
        '1542:DRUM_BOIL_SAFETY_CHECK,'
        '1543:DRUM_BOIL_TESTING,'
        '1544:DRY_SCRUB_INSPECTION,'
        '1545:DRY_SCRUB_SAFETY_CHECK,'
        '1546:DRY_SCRUB_TESTING,'
        '1547:DTH_DRILL_INSPECTION,'
        '1548:DTH_DRILL_SAFETY_CHECK,'
        '1549:DTH_DRILL_TESTING,'
        '1550:DUST_COLL_INSPECTION,'
        '1551:DUST_COLL_SAFETY_CHECK,'
        '1552:DUST_COLL_TESTING,'
        '1553:ECOAT_INSPECTION,'
        '1554:ECOAT_SAFETY_CHECK,'
        '1555:ECOAT_TESTING,'
        '1556:EDM_MACH_INSPECTION,'
        '1557:EDM_MACH_SAFETY_CHECK,'
        '1558:EDM_MACH_TESTING,'
        '1559:ENC_FLARE_INSPECTION,'
        '1560:ENC_FLARE_SAFETY_CHECK,'
        '1561:ENC_FLARE_TESTING,'
        '1562:END_SUCT_INSPECTION,'
        '1563:END_SUCT_SAFETY_CHECK,'
        '1564:END_SUCT_TESTING,'
        '1565:ESP_INSPECTION,'
        '1566:ESP_SAFETY_CHECK,'
        '1567:ESP_TESTING,'
        '1568:EVAPORATOR_INSPECTION,'
        '1569:EVAPORATOR_SAFETY_CHECK,'
        '1570:EVAPORATOR_TESTING,'
        '1571:EXPL_PR_INSPECTION,'
        '1572:EXPL_PR_SAFETY_CHECK,'
        '1573:EXPL_PR_TESTING,'
        '1574:EXTR_MACH_INSPECTION,'
        '1575:EXTR_MACH_SAFETY_CHECK,'
        '1576:EXTR_MACH_TESTING,'
        '1577:FF_EVAP_INSPECTION,'
        '1578:FF_EVAP_SAFETY_CHECK,'
        '1579:FF_EVAP_TESTING,'
        '1580:FGD_ABSORB_INSPECTION,'
        '1581:FGD_ABSORB_SAFETY_CHECK,'
        '1582:FGD_ABSORB_TESTING,'
        '1583:FIX_BED_REACT_INSPECTION,'
        '1584:FIX_BED_REACT_SAFETY_CHECK,'
        '1585:FIX_BED_REACT_TESTING,'
        '1586:FLARE_STK_INSPECTION,'
        '1587:FLARE_STK_SAFETY_CHECK,'
        '1588:FLARE_STK_TESTING,'
        '1589:FLOWLINE_INSPECTION,'
        '1590:FLOWLINE_SAFETY_CHECK,'
        '1591:FLOWLINE_TESTING,'
        '1592:FB_DRY_INSPECTION,'
        '1593:FB_DRY_SAFETY_CHECK,'
        '1594:FB_DRY_TESTING,'
        '1595:FLUID_BED_REACT_INSPECTION,'
        '1596:FLUID_BED_REACT_SAFETY_CHECK,'
        '1597:FLUID_BED_REACT_TESTING,'
        '1598:FLY_ASH_SILO_INSPECTION,'
        '1599:FLY_ASH_SILO_SAFETY_CHECK,'
        '1600:FLY_ASH_SILO_TESTING,'
        '1601:FC_EVAP_INSPECTION,'
        '1602:FC_EVAP_SAFETY_CHECK,'
        '1603:FC_EVAP_TESTING,'
        '1604:FORKLIFT_INSPECTION,'
        '1605:FORKLIFT_SAFETY_CHECK,'
        '1606:FORKLIFT_TESTING,'
        '1607:FREEZE_DRY_INSPECTION,'
        '1608:FREEZE_DRY_SAFETY_CHECK,'
        '1609:FREEZE_DRY_TESTING,'
        '1610:GAS_COMP_INSPECTION,'
        '1611:GAS_COMP_SAFETY_CHECK,'
        '1612:GAS_COMP_TESTING,'
        '1613:GAS_DETECT_INSPECTION,'
        '1614:GAS_DETECT_SAFETY_CHECK,'
        '1615:GAS_DETECT_TESTING,'
        '1616:GAS_TURB_INSPECTION,'
        '1617:GAS_TURB_SAFETY_CHECK,'
        '1618:GAS_TURB_TESTING,'
        '1619:GATH_LINE_INSPECTION,'
        '1620:GATH_LINE_SAFETY_CHECK,'
        '1621:GATH_LINE_TESTING,'
        '1622:GIS_SWGR_INSPECTION,'
        '1623:GIS_SWGR_SAFETY_CHECK,'
        '1624:GIS_SWGR_TESTING,'
        '1625:GRIND_MACH_INSPECTION,'
        '1626:GRIND_MACH_SAFETY_CHECK,'
        '1627:GRIND_MACH_TESTING,'
        '1628:GYR_CRUSH_INSPECTION,'
        '1629:GYR_CRUSH_SAFETY_CHECK,'
        '1630:GYR_CRUSH_TESTING,'
        '1631:HAUL_TRK_INSPECTION,'
        '1632:HAUL_TRK_SAFETY_CHECK,'
        '1633:HAUL_TRK_TESTING,'
        '1634:HEATER_TREAT_INSPECTION,'
        '1635:HEATER_TREAT_SAFETY_CHECK,'
        '1636:HEATER_TREAT_TESTING,'
        '1637:HP_HEATER_INSPECTION,'
        '1638:HP_HEATER_SAFETY_CHECK,'
        '1639:HP_HEATER_TESTING,'
        '1640:HRSG_INSPECTION,'
        '1641:HRSG_SAFETY_CHECK,'
        '1642:HRSG_TESTING,'
        '1643:HYD_PRESS_INSPECTION,'
        '1644:HYD_PRESS_SAFETY_CHECK,'
        '1645:HYD_PRESS_TESTING,'
        '1646:HYD_SHOVEL_INSPECTION,'
        '1647:HYD_SHOVEL_SAFETY_CHECK,'
        '1648:HYD_SHOVEL_TESTING,'
        '1649:H2_GEN_INSPECTION,'
        '1650:H2_GEN_SAFETY_CHECK,'
        '1651:H2_GEN_TESTING,'
        '1652:IMP_CRUSH_INSPECTION,'
        '1653:IMP_CRUSH_SAFETY_CHECK,'
        '1654:IMP_CRUSH_TESTING,'
        '1655:INDIR_HEAT_INSPECTION,'
        '1656:INDIR_HEAT_SAFETY_CHECK,'
        '1657:INDIR_HEAT_TESTING,'
        '1658:INJECT_MACH_INSPECTION,'
        '1659:INJECT_MACH_SAFETY_CHECK,'
        '1660:INJECT_MACH_TESTING,'
        '1661:JAW_CRUSH_INSPECTION,'
        '1662:JAW_CRUSH_SAFETY_CHECK,'
        '1663:JAW_CRUSH_TESTING,'
        '1664:JET_MIXER_INSPECTION,'
        '1665:JET_MIXER_SAFETY_CHECK,'
        '1666:JET_MIXER_TESTING,'
        '1667:LABEL_MACH_INSPECTION,'
        '1668:LABEL_MACH_SAFETY_CHECK,'
        '1669:LABEL_MACH_TESTING,'
        '1670:LEAF_FILT_INSPECTION,'
        '1671:LEAF_FILT_SAFETY_CHECK,'
        '1672:LEAF_FILT_TESTING,'
        '1673:LIME_SLUR_PUMP_INSPECTION,'
        '1674:LIME_SLUR_PUMP_SAFETY_CHECK,'
        '1675:LIME_SLUR_PUMP_TESTING,'
        '1676:LIQ_RING_COMP_INSPECTION,'
        '1677:LIQ_RING_COMP_SAFETY_CHECK,'
        '1678:LIQ_RING_COMP_TESTING,'
        '1679:LWSHEARER_INSPECTION,'
        '1680:LWSHEARER_SAFETY_CHECK,'
        '1681:LWSHEARER_TESTING,'
        '1682:LP_HEATER_INSPECTION,'
        '1683:LP_HEATER_SAFETY_CHECK,'
        '1684:LP_HEATER_TESTING,'
        '1685:MAG_DRIVE_PUMP_INSPECTION,'
        '1686:MAG_DRIVE_PUMP_SAFETY_CHECK,'
        '1687:MAG_DRIVE_PUMP_TESTING,'
        '1688:COOL_TWR_INSPECTION,'
        '1689:COOL_TWR_SAFETY_CHECK,'
        '1690:COOL_TWR_TESTING,'
        '1691:MECH_PRESS_INSPECTION,'
        '1692:MECH_PRESS_SAFETY_CHECK,'
        '1693:MECH_PRESS_TESTING,'
        '1694:METER_PUMP_INSPECTION,'
        '1695:METER_PUMP_SAFETY_CHECK,'
        '1696:METER_PUMP_TESTING,'
        '1697:MIG_WELD_INSPECTION,'
        '1698:MIG_WELD_SAFETY_CHECK,'
        '1699:MIG_WELD_TESTING,'
        '1700:MINE_DW_PUMP_INSPECTION,'
        '1701:MINE_DW_PUMP_SAFETY_CHECK,'
        '1702:MINE_DW_PUMP_TESTING,'
        '1703:MINE_HOIST_INSPECTION,'
        '1704:MINE_HOIST_SAFETY_CHECK,'
        '1705:MINE_HOIST_TESTING,'
        '1706:MINE_FAN_INSPECTION,'
        '1707:MINE_FAN_SAFETY_CHECK,'
        '1708:MINE_FAN_TESTING,'
        '1709:MOL_SIEVE_INSPECTION,'
        '1710:MOL_SIEVE_SAFETY_CHECK,'
        '1711:MOL_SIEVE_TESTING,'
        '1712:MOTOR_GRADER_INSPECTION,'
        '1713:MOTOR_GRADER_SAFETY_CHECK,'
        '1714:MOTOR_GRADER_TESTING,'
        '1715:MULTIPHASE_INSPECTION,'
        '1716:MULTIPHASE_SAFETY_CHECK,'
        '1717:MULTIPHASE_TESTING,'
        '1718:MULTISTG_INSPECTION,'
        '1719:MULTISTG_SAFETY_CHECK,'
        '1720:MULTISTG_TESTING,'
        '1721:NAT_COOL_TWR_INSPECTION,'
        '1722:NAT_COOL_TWR_SAFETY_CHECK,'
        '1723:NAT_COOL_TWR_TESTING,'
        '1724:OT_BOIL_INSPECTION,'
        '1725:OT_BOIL_SAFETY_CHECK,'
        '1726:OT_BOIL_TESTING,'
        '1727:ORDER_PICK_INSPECTION,'
        '1728:ORDER_PICK_SAFETY_CHECK,'
        '1729:ORDER_PICK_TESTING,'
        '1730:ORIF_METER_INSPECTION,'
        '1731:ORIF_METER_SAFETY_CHECK,'
        '1732:ORIF_METER_TESTING,'
        '1733:OH_CONV_INSPECTION,'
        '1734:OH_CONV_SAFETY_CHECK,'
        '1735:OH_CONV_TESTING,'
        '1736:OVL_CONV_INSPECTION,'
        '1737:OVL_CONV_SAFETY_CHECK,'
        '1738:OVL_CONV_TESTING,'
        '1739:PKG_MACH_INSPECTION,'
        '1740:PKG_MACH_SAFETY_CHECK,'
        '1741:PKG_MACH_TESTING,'
        '1742:PACKED_COL_INSPECTION,'
        '1743:PACKED_COL_SAFETY_CHECK,'
        '1744:PACKED_COL_TESTING,'
        '1745:PALLET_JACK_INSPECTION,'
        '1746:PALLET_JACK_SAFETY_CHECK,'
        '1747:PALLET_JACK_TESTING,'
        '1748:PALLETIZER_INSPECTION,'
        '1749:PALLETIZER_SAFETY_CHECK,'
        '1750:PALLETIZER_TESTING,'
        '1751:PIG_LAUNCH_INSPECTION,'
        '1752:PIG_LAUNCH_SAFETY_CHECK,'
        '1753:PIG_LAUNCH_TESTING,'
        '1754:PIG_REC_INSPECTION,'
        '1755:PIG_REC_SAFETY_CHECK,'
        '1756:PIG_REC_TESTING,'
        '1757:PLATE_EX_OG_INSPECTION,'
        '1758:PLATE_EX_OG_SAFETY_CHECK,'
        '1759:PLATE_EX_OG_TESTING,'
        '1760:PFR_INSPECTION,'
        '1761:PFR_SAFETY_CHECK,'
        '1762:PFR_TESTING,'
        '1763:POWDER_BOOTH_INSPECTION,'
        '1764:POWDER_BOOTH_SAFETY_CHECK,'
        '1765:POWDER_BOOTH_TESTING,'
        '1766:PRESS_FILT_INSPECTION,'
        '1767:PRESS_FILT_SAFETY_CHECK,'
        '1768:PRESS_FILT_TESTING,'
        '1769:PROC_BLOW_INSPECTION,'
        '1770:PROC_BLOW_SAFETY_CHECK,'
        '1771:PROC_BLOW_TESTING,'
        '1772:PROD_SEP_INSPECTION,'
        '1773:PROD_SEP_SAFETY_CHECK,'
        '1774:PROD_SEP_TESTING,'
        '1775:REACH_TRK_INSPECTION,'
        '1776:REACH_TRK_SAFETY_CHECK,'
        '1777:REACH_TRK_TESTING,'
        '1778:REACT_DIST_INSPECTION,'
        '1779:REACT_DIST_SAFETY_CHECK,'
        '1780:REACT_DIST_TESTING,'
        '1781:RECIP_AIR_COMP_INSPECTION,'
        '1782:RECIP_AIR_COMP_SAFETY_CHECK,'
        '1783:RECIP_AIR_COMP_TESTING,'
        '1784:RECIP_COMP_OG_INSPECTION,'
        '1785:RECIP_COMP_OG_SAFETY_CHECK,'
        '1786:RECIP_COMP_OG_TESTING,'
        '1787:RECLAIMER_INSPECTION,'
        '1788:RECLAIMER_SAFETY_CHECK,'
        '1789:RECLAIMER_TESTING,'
        '1790:RES_WELD_INSPECTION,'
        '1791:RES_WELD_SAFETY_CHECK,'
        '1792:RES_WELD_TESTING,'
        '1793:ROD_MILL_INSPECTION,'
        '1794:ROD_MILL_SAFETY_CHECK,'
        '1795:ROD_MILL_TESTING,'
        '1796:ROLL_CONV_INSPECTION,'
        '1797:ROLL_CONV_SAFETY_CHECK,'
        '1798:ROLL_CONV_TESTING,'
        '1799:ROOF_BOLT_INSPECTION,'
        '1800:ROOF_BOLT_SAFETY_CHECK,'
        '1801:ROOF_BOLT_TESTING,'
        '1802:RTU_INSPECTION,'
        '1803:RTU_SAFETY_CHECK,'
        '1804:RTU_TESTING,'
        '1805:ROPE_SHOVEL_INSPECTION,'
        '1806:ROPE_SHOVEL_SAFETY_CHECK,'
        '1807:ROPE_SHOVEL_TESTING,'
        '1808:ROT_DRILL_INSPECTION,'
        '1809:ROT_DRILL_SAFETY_CHECK,'
        '1810:ROT_DRILL_TESTING,'
        '1811:ROT_DRY_INSPECTION,'
        '1812:ROT_DRY_SAFETY_CHECK,'
        '1813:ROT_DRY_TESTING,'
        '1814:ROT_SCREW_COMP_INSPECTION,'
        '1815:ROT_SCREW_COMP_SAFETY_CHECK,'
        '1816:ROT_SCREW_COMP_TESTING,'
        '1817:RVF_INSPECTION,'
        '1818:RVF_SAFETY_CHECK,'
        '1819:RVF_TESTING,'
        '1820:SAG_MILL_INSPECTION,'
        '1821:SAG_MILL_SAFETY_CHECK,'
        '1822:SAG_MILL_TESTING,'
        '1823:SCARA_ROBOT_INSPECTION,'
        '1824:SCARA_ROBOT_SAFETY_CHECK,'
        '1825:SCARA_ROBOT_TESTING,'
        '1826:SCR_INSPECTION,'
        '1827:SCR_SAFETY_CHECK,'
        '1828:SCR_TESTING,'
        '1829:SCREW_COMP_OG_INSPECTION,'
        '1830:SCREW_COMP_OG_SAFETY_CHECK,'
        '1831:SCREW_COMP_OG_TESTING,'
        '1832:SERVO_PRESS_INSPECTION,'
        '1833:SERVO_PRESS_SAFETY_CHECK,'
        '1834:SERVO_PRESS_TESTING,'
        '1835:SHALE_SHAKE_INSPECTION,'
        '1836:SHALE_SHAKE_SAFETY_CHECK,'
        '1837:SHALE_SHAKE_TESTING,'
        '1838:SHELL_TUBE_OG_INSPECTION,'
        '1839:SHELL_TUBE_OG_SAFETY_CHECK,'
        '1840:SHELL_TUBE_OG_TESTING,'
        '1841:SHRINK_WRAP_INSPECTION,'
        '1842:SHRINK_WRAP_SAFETY_CHECK,'
        '1843:SHRINK_WRAP_TESTING,'
        '1844:SINGLE_INSPECTION,'
        '1845:SINGLE_SAFETY_CHECK,'
        '1846:SINGLE_TESTING,'
        '1847:SLUG_CATCH_INSPECTION,'
        '1848:SLUG_CATCH_SAFETY_CHECK,'
        '1849:SLUG_CATCH_TESTING,'
        '1850:SLURRY_PUMP_INSPECTION,'
        '1851:SLURRY_PUMP_SAFETY_CHECK,'
        '1852:SLURRY_PUMP_TESTING,'
        '1853:SPH_TANK_INSPECTION,'
        '1854:SPH_TANK_SAFETY_CHECK,'
        '1855:SPH_TANK_TESTING,'
        '1856:SPIRAL_EX_INSPECTION,'
        '1857:SPIRAL_EX_SAFETY_CHECK,'
        '1858:SPIRAL_EX_TESTING,'
        '1859:SPRAY_BOOTH_INSPECTION,'
        '1860:SPRAY_BOOTH_SAFETY_CHECK,'
        '1861:SPRAY_BOOTH_TESTING,'
        '1862:SPRAY_DRY_INSPECTION,'
        '1863:SPRAY_DRY_SAFETY_CHECK,'
        '1864:SPRAY_DRY_TESTING,'
        '1865:STACKER_INSPECTION,'
        '1866:STACKER_SAFETY_CHECK,'
        '1867:STACKER_TESTING,'
        '1868:STATIC_MIXER_INSPECTION,'
        '1869:STATIC_MIXER_SAFETY_CHECK,'
        '1870:STATIC_MIXER_TESTING,'
        '1871:STEAM_TURB_INSPECTION,'
        '1872:STEAM_TURB_SAFETY_CHECK,'
        '1873:STEAM_TURB_TESTING,'
        '1874:STEP_UP_XFMR_INSPECTION,'
        '1875:STEP_UP_XFMR_SAFETY_CHECK,'
        '1876:STEP_UP_XFMR_TESTING,'
        '1877:STOR_SILO_INSPECTION,'
        '1878:STOR_SILO_SAFETY_CHECK,'
        '1879:STOR_SILO_TESTING,'
        '1880:SUBM_CENT_INSPECTION,'
        '1881:SUBM_CENT_SAFETY_CHECK,'
        '1882:SUBM_CENT_TESTING,'
        '1883:SUB_MANIFOLD_INSPECTION,'
        '1884:SUB_MANIFOLD_SAFETY_CHECK,'
        '1885:SUB_MANIFOLD_TESTING,'
        '1886:SUBSEA_PIPE_INSPECTION,'
        '1887:SUBSEA_PIPE_SAFETY_CHECK,'
        '1888:SUBSEA_PIPE_TESTING,'
        '1889:SUBSEA_TREE_INSPECTION,'
        '1890:SUBSEA_TREE_SAFETY_CHECK,'
        '1891:SUBSEA_TREE_TESTING,'
        '1892:TEFC_INSPECTION,'
        '1893:TEFC_SAFETY_CHECK,'
        '1894:TEFC_TESTING,'
        '1895:DEHYDRATOR_INSPECTION,'
        '1896:DEHYDRATOR_SAFETY_CHECK,'
        '1897:DEHYDRATOR_TESTING,'
        '1898:TEST_SEP_INSPECTION,'
        '1899:TEST_SEP_SAFETY_CHECK,'
        '1900:TEST_SEP_TESTING,'
        '1901:THERMO_MACH_INSPECTION,'
        '1902:THERMO_MACH_SAFETY_CHECK,'
        '1903:THERMO_MACH_TESTING,'
        '1904:TIG_WELD_INSPECTION,'
        '1905:TIG_WELD_SAFETY_CHECK,'
        '1906:TIG_WELD_TESTING,'
        '1907:TOP_DRIVE_INSPECTION,'
        '1908:TOP_DRIVE_SAFETY_CHECK,'
        '1909:TOP_DRIVE_TESTING,'
        '1910:TRAY_COL_INSPECTION,'
        '1911:TRAY_COL_SAFETY_CHECK,'
        '1912:TRAY_COL_TESTING,'
        '1913:TRIP_HRSG_INSPECTION,'
        '1914:TRIP_HRSG_SAFETY_CHECK,'
        '1915:TRIP_HRSG_TESTING,'
        '1916:TRIPLEX_PUMP_INSPECTION,'
        '1917:TRIPLEX_PUMP_SAFETY_CHECK,'
        '1918:TRIPLEX_PUMP_TESTING,'
        '1919:GEN_TG_INSPECTION,'
        '1920:GEN_TG_SAFETY_CHECK,'
        '1921:GEN_TG_TESTING,'
        '1922:ULTRA_METER_INSPECTION,'
        '1923:ULTRA_METER_SAFETY_CHECK,'
        '1924:ULTRA_METER_TESTING,'
        '1925:UNIT_XFMR_INSPECTION,'
        '1926:UNIT_XFMR_SAFETY_CHECK,'
        '1927:UNIT_XFMR_TESTING,'
        '1928:VERT_MILL_INSPECTION,'
        '1929:VERT_MILL_SAFETY_CHECK,'
        '1930:VERT_MILL_TESTING,'
        '1931:VIB_FEED_INSPECTION,'
        '1932:VIB_FEED_SAFETY_CHECK,'
        '1933:VIB_FEED_TESTING,'
        '1934:WELLHEAD_INSPECTION,'
        '1935:WELLHEAD_SAFETY_CHECK,'
        '1936:WELLHEAD_TESTING,'
        '1937:WET_SCRUB_INSPECTION,'
        '1938:WET_SCRUB_SAFETY_CHECK,'
        '1939:WET_SCRUB_TESTING,'
        '1940:WHL_LOAD_INSPECTION,'
        '1941:WHL_LOAD_SAFETY_CHECK,'
        '1942:WHL_LOAD_TESTING,'
        '1943:WINDER_MOTOR_INSPECTION,'
        '1944:WINDER_MOTOR_SAFETY_CHECK,'
        '1945:WINDER_MOTOR_TESTING';
    v_manifest_count INTEGER;
    v_matched_count INTEGER;
    v_present_id_count INTEGER;
    v_classified INTEGER;
    v_applicability INTEGER;
BEGIN
    -- 1. the manifest itself must be the ratified 846-identity set
    SELECT count(*) INTO v_manifest_count
      FROM (SELECT split_part(elem, ':', 1)::INTEGER AS template_id,
                   split_part(elem, ':', 2)             AS template_code
              FROM unnest(string_to_array(v_manifest, ',')) AS mf(elem)) m;

    IF v_manifest_count <> 846 THEN
        RAISE EXCEPTION 'M6.3 manifest integrity failure: expected 846 frozen identities, found %',
            v_manifest_count USING ERRCODE = 'check_violation';
    END IF;

    -- The manifest must itself be the ratified identity interval. Expressed as a
    -- contiguity relation over the manifest alone, so no row-range scan and no
    -- range predicate ever participates in classification: if the manifest holds
    -- N distinct ids whose span is exactly N, the ids are necessarily contiguous.
    IF (SELECT max(split_part(elem, ':', 1)::INTEGER)
               - min(split_part(elem, ':', 1)::INTEGER) + 1
          FROM unnest(string_to_array(v_manifest, ',')) AS mf(elem)) <> v_manifest_count THEN
        RAISE EXCEPTION 'M6.3 manifest integrity failure: identities are not the ratified contiguous interval'
            USING ERRCODE = 'check_violation';
    END IF;

    -- 2. how much of the corpus is present?
    --
    -- Two distinct counts are needed, and conflating them was a defect: "how many
    -- frozen identities are present by ID" and "how many match the frozen identity
    -- EXACTLY (id AND code)". A corpus whose rows all sit on frozen manifest IDs
    -- but whose codes do not match produces an exact-match count of zero — which
    -- is indistinguishable from a genuinely absent corpus if only the exact count
    -- is consulted. That let a tampered or systematically mis-coded corpus be
    -- silently treated as absent: the migration reported success, classified
    -- nothing, and backfilled no applicability.
    --
    -- Presence is therefore decided by ID, and exactness by the full identity.
    SELECT count(*) INTO v_present_id_count
      FROM task_templates t
      JOIN (SELECT DISTINCT split_part(elem, ':', 1)::INTEGER AS template_id
              FROM unnest(string_to_array(v_manifest, ',')) AS mf(elem)) m
        ON m.template_id = t.id;

    SELECT count(*) INTO v_matched_count
      FROM task_templates t
      JOIN (SELECT split_part(elem, ':', 1)::INTEGER AS template_id,
                   split_part(elem, ':', 2)             AS template_code
              FROM unnest(string_to_array(v_manifest, ',')) AS mf(elem)) m
        ON m.template_id = t.id
       AND m.template_code = t.template_code;

    -- Genuinely absent corpus: no frozen manifest identity is present at all.
    -- Rows outside the manifest (ids that are not ratified identities) are none of
    -- this migration's business and are tolerated and preserved untouched.
    IF v_present_id_count = 0 THEN
        RAISE NOTICE 'M6.3: reconciled legacy corpus absent - no origin classification performed (allowed no-op)';
        RETURN;
    END IF;

    -- Any frozen identity present without its ratified code is an identity
    -- collision at a reserved identity: presence and identity disagree, so the
    -- migration refuses and rolls back rather than guessing which is right.
    IF v_matched_count <> v_present_id_count THEN
        RAISE EXCEPTION 'M6.3 legacy corpus is INCONSISTENT: % ratified identity id(s) present but only % match the frozen identity exactly. A reserved identity carries a non-ratified code. Refusing to classify.',
            v_present_id_count, v_matched_count USING ERRCODE = 'check_violation';
    END IF;

    IF v_matched_count <> v_manifest_count THEN
        RAISE EXCEPTION 'M6.3 legacy corpus is PARTIAL or INCONSISTENT: % of % ratified identities present. Refusing to partially classify.',
            v_matched_count, v_manifest_count USING ERRCODE = 'check_violation';
    END IF;

    -- 3. classify exactly the reconciled corpus. Idempotent: only unclassified rows
    --    are touched, and content_origin is immutable thereafter, so a second
    --    execution matches zero rows.
    UPDATE task_templates t
       SET content_origin = 'legacy_generated'
     WHERE t.content_origin IS NULL
       AND EXISTS (
           SELECT 1 FROM (SELECT split_part(elem, ':', 1)::INTEGER AS template_id,
                                 split_part(elem, ':', 2)             AS template_code
                            FROM unnest(string_to_array(v_manifest, ',')) AS mf(elem)) m
            WHERE m.template_id = t.id AND m.template_code = t.template_code);
    GET DIAGNOSTICS v_classified = ROW_COUNT;

    -- 4. applicability backfill: the declared Equipment Type is copied verbatim as
    --    the primary anchor. Superseded and retired Equipment Types are NOT
    --    remapped and no taxonomy resolution is applied - declaration is preserved
    --    and governed reconciliation happens later, by humans.
    INSERT INTO task_template_equipment_types (task_template_id, equipment_type_id, is_primary)
    SELECT t.id, t.equipment_type_id, TRUE
      FROM task_templates t
      JOIN (SELECT split_part(elem, ':', 1)::INTEGER AS template_id,
                   split_part(elem, ':', 2)             AS template_code
              FROM unnest(string_to_array(v_manifest, ',')) AS mf(elem)) m
        ON m.template_id = t.id
       AND m.template_code = t.template_code
     WHERE t.equipment_type_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM task_template_equipment_types x
            WHERE x.task_template_id = t.id)
    ON CONFLICT (task_template_id, equipment_type_id) DO NOTHING;
    GET DIAGNOSTICS v_applicability = ROW_COUNT;

    RAISE NOTICE 'M6.3: legacy corpus verified (% identities); % row(s) classified; % applicability row(s) inserted',
        v_manifest_count, v_classified, v_applicability;
END
$$;
